KhronosGroup/Vulkan-Hpp

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix gcc/clang includes and warnings

README.md, VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Remove nvidia references

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Add missing "std::" to nullptr_t.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Add support for template strings in code generator to make the code generator more readable.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Update to Vulkan 1.0.55

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
- Add support for the new alias tag
=> Update to Vulkan 1.0.66

README.md, VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Introduce VULKAN_HPP_ASSERT, to allow custom assert.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Introduce simplified overloads for destroy* and free* functions

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix Deleter objects for Device and DeviceMemory.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix ObjectDeleter arguments for NoParent cases.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Use constexpr on simple class constructors.

samples/06_InitDepthBuffer/06_InitDepthBuffer.cpp, samples/08_InitPipelineLayout/08_InitPipelineLayout.cpp, samples/09_InitDescriptorSet/09_InitDescriptorSet.cpp, samples/09_InitDescriptorSet/CMakeLists.txt, samples/10_InitRenderPass/10_InitRenderPass.cpp, samples/10_InitRenderPass/CMakeLists.txt
+ add some missing exit code to some samples.
=> Samples on vulkan.hpp: 09_InitDescriptorSet.cpp, 10_InitRenderPass

CMakeLists.txt, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/01_InitInstance/01_InitInstance.cpp, samples/02_EnumerateDevices/02_EnumerateDevices.cpp, samples/03_InitDevice/03_InitDevice.cpp, samples/04_InitCommandBuffer/04_InitCommandBuffer.cpp, samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/06_InitDepthBuffer/06_InitDepthBuffer.cpp, samples/07_InitUniformBuffer/07_InitUniformBuffer.cpp, samples/08_InitPipelineLayout/08_InitPipelineLayout.cpp, samples/09_InitDescriptorSet/09_InitDescriptorSet.cpp, samples/10_InitRenderPass/10_InitRenderPass.cpp, vulkan/vulkan.hpp
=> Switch to warning level 4

VulkanHppGenerator.cpp
Improved checking in enum/bitmask handling.
=> Corrected handling of aliased structure types;

CMakeLists.txt, README.md, VulkanHppGenerator.cpp, tests/CMakeLists.txt, tests/StructureChain/CMakeLists.txt, tests/StructureChain/StructureChain.cpp, vulkan/vulkan.hpp
+ adjusted readme.md accordingly
+ added (a first!) test project
=> Corrected functions dealing with StructureChains.

VulkanHppGenerator.cpp, tests/StructureChain/StructureChain.cpp, vulkan/vulkan.hpp
=> Extend checking of StructureChains to allow transitive extension.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Check result in two-step functions like enumeratePhysicalDevices

VulkanHppGenerator.cpp, tests/DeviceFunctions/DeviceFunctions.cpp, vulkan/vulkan.hpp
=> Fix issue with unused parameter "vectorAllocator" in some functions.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Correct usage of platform/protect information.

.gitmodules, CMakeLists.txt, samples/11_InitShaders/11_InitShaders.cpp, samples/11_InitShaders/CMakeLists.txt
=> Add sample 11_InitShaders

samples/01_InitInstance/01_InitInstance.cpp, samples/02_EnumerateDevices/02_EnumerateDevices.cpp, samples/02_EnumerateDevices/CMakeLists.txt, samples/03_InitDevice/03_InitDevice.cpp, samples/03_InitDevice/CMakeLists.txt, samples/04_InitCommandBuffer/04_InitCommandBuffer.cpp, samples/04_InitCommandBuffer/CMakeLists.txt, samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/05_InitSwapchain/CMakeLists.txt, samples/06_InitDepthBuffer/06_InitDepthBuffer.cpp, samples/06_InitDepthBuffer/CMakeLists.txt, samples/07_InitUniformBuffer/07_InitUniformBuffer.cpp, samples/07_InitUniformBuffer/CMakeLists.txt, samples/08_InitPipelineLayout/08_InitPipelineLayout.cpp, samples/08_InitPipelineLayout/CMakeLists.txt, samples/09_InitDescriptorSet/09_InitDescriptorSet.cpp, samples/09_InitDescriptorSet/CMakeLists.txt, samples/10_InitRenderPass/10_InitRenderPass.cpp, samples/10_InitRenderPass/CMakeLists.txt, samples/11_InitShaders/11_InitShaders.cpp, samples/11_InitShaders/CMakeLists.txt, samples/utils/utils.cpp, samples/utils/utils.hpp
- introduce samples/utils functions in namespace vk::su (vulkan sample utils)
- introduce usage of debugReportCallback
=> Cleanup on Samples

samples/07_InitUniformBuffer/07_InitUniformBuffer.cpp, samples/09_InitDescriptorSet/09_InitDescriptorSet.cpp, samples/11_InitShaders/11_InitShaders.cpp, samples/12_InitFrameBuffers/12_InitFrameBuffers.cpp, samples/12_InitFrameBuffers/CMakeLists.txt, samples/13_InitVertexBuffer/13_InitVertexBuffer.cpp, samples/13_InitVertexBuffer/CMakeLists.txt, samples/14_InitPipeline/14_InitPipeline.cpp, samples/14_InitPipeline/CMakeLists.txt, samples/15_DrawCube/15_DrawCube.cpp, samples/15_DrawCube/CMakeLists.txt, samples/utils/geometries.hpp, samples/utils/math.cpp, samples/utils/math.hpp, samples/utils/shaders.cpp, samples/utils/shaders.hpp, samples/utils/utils.cpp, samples/utils/utils.hpp
+ 12_InitFrameBuffers, 13_InitVertexBuffer, 14_InitPipeline, 15_DrawCube;
+ extend utilities and add utilities on geometries, math, and shaders
+ slightly adjust some other samples
=> Extend set of samples

samples/01_InitInstance/CMakeLists.txt, samples/02_EnumerateDevices/CMakeLists.txt, samples/03_InitDevice/CMakeLists.txt, samples/04_InitCommandBuffer/CMakeLists.txt, samples/05_InitSwapchain/CMakeLists.txt, samples/06_InitDepthBuffer/CMakeLists.txt, samples/07_InitUniformBuffer/CMakeLists.txt, samples/08_InitPipelineLayout/CMakeLists.txt, samples/09_InitDescriptorSet/CMakeLists.txt, samples/10_InitRenderPass/CMakeLists.txt, samples/11_InitShaders/CMakeLists.txt, samples/12_InitFrameBuffers/CMakeLists.txt, samples/13_InitVertexBuffer/CMakeLists.txt, samples/14_InitPipeline/CMakeLists.txt, samples/15_DrawCube/CMakeLists.txt, samples/CMakeLists.txt, tests/CMakeLists.txt, tests/DeviceFunctions/CMakeLists.txt, tests/NoExceptions/CMakeLists.txt, tests/StructureChain/CMakeLists.txt
=> Use CMake's find_package to locate vulkan for samples and tests.

samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/InputAttachment/InputAttachment.cpp, samples/utils/utils.cpp
+ fixed one issue caught by that layer in InputAttachment.
=> [VulkanHpp] changed to "VK_LAYER_KHRONOS_validation" as validation layer

samples/DrawTexturedCube/DrawTexturedCube.cpp, samples/DynamicUniform/DynamicUniform.cpp, samples/EnumerateDevicesAdvanced/EnumerateDevicesAdvanced.cpp, samples/ImmutableSampler/ImmutableSampler.cpp, samples/InputAttachment/InputAttachment.cpp, samples/MultipleSets/MultipleSets.cpp, samples/OcclusionQuery/CMakeLists.txt, samples/OcclusionQuery/OcclusionQuery.cpp, samples/PipelineCache/CMakeLists.txt, samples/PipelineCache/PipelineCache.cpp, samples/PipelineDerivative/CMakeLists.txt, samples/PipelineDerivative/PipelineDerivative.cpp, samples/PushConstants/CMakeLists.txt, samples/PushConstants/PushConstants.cpp, samples/PushDescriptors/CMakeLists.txt, samples/PushDescriptors/PushDescriptors.cpp, samples/utils/math.cpp, samples/utils/shaders.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp
+ some minor improvements in some samples, math, shaders and utils.
=> Add sample OcclusionQuery, PipelineCache, PipelineDerivative, PushConstants, and PushDescriptors

VulkanHppGenerator.cpp
=> Add handling of "comment" to disabled extensions.

samples/06_InitDepthBuffer/06_InitDepthBuffer.cpp, samples/09_InitDescriptorSet/09_InitDescriptorSet.cpp, samples/10_InitRenderPass/10_InitRenderPass.cpp, samples/12_InitFrameBuffers/12_InitFrameBuffers.cpp, samples/13_InitVertexBuffer/13_InitVertexBuffer.cpp, samples/14_InitPipeline/14_InitPipeline.cpp, samples/15_DrawCube/15_DrawCube.cpp, samples/CopyBlitImage/CopyBlitImage.cpp, samples/DynamicUniform/DynamicUniform.cpp, samples/ImmutableSampler/ImmutableSampler.cpp, samples/InitTexture/InitTexture.cpp, samples/InputAttachment/InputAttachment.cpp, samples/MultipleSets/MultipleSets.cpp, samples/OcclusionQuery/OcclusionQuery.cpp, samples/PipelineCache/PipelineCache.cpp, samples/PipelineDerivative/PipelineDerivative.cpp, samples/PushConstants/PushConstants.cpp, samples/PushDescriptors/PushDescriptors.cpp, samples/SecondaryCommandBuffer/CMakeLists.txt, samples/SecondaryCommandBuffer/SecondaryCommandBuffer.cpp, samples/SeparateImageSampler/CMakeLists.txt, samples/SeparateImageSampler/SeparateImageSampler.cpp, samples/utils/math.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp
+ made some helper functions more explicit.
=> Add samples SecondaryCommandBuffer and SeparateImageSampler.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Filter out multi-bit values for to_string function on FlagBits.

VulkanHppGenerator.cpp
This is required to prevent breakage from an upcoming extension.
=> Only emit union constructors and setters if !returnedonly

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix wrong naming of complex union member types.

VulkanHppGenerator.cpp
=> Move check for redundant aliased enum values from read to write.

.travis.yml, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Introduce usage of constexpr for constructors of structs.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Make logical operators on flags constexpr.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
* ResultValue constexpr was incorrect
* msvc 2015 says operator== for flagbits is ambigious when not calling them through operator==(bits, bits)
=> Fix minor issues revealed by vkcubepp

.appveyor.yml
MSVC is a major platform, so having some automated builds on it can certainly be useful.
For example, this exposes #343.
=> Add an appveyor config

CMakeLists.txt
This CL adds VULKAN_HPP_VULKAN_HEADERS_SRC_DIR and VULKAN_HPP_PATH
variables to the CMakeLists file.
=> Allow setting vulkan paths.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Currently just registerEventEXTUnique and registerDisplayEventEXTUnique
=> Add unique-versions of "Register"-functions

samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/utils/utils.cpp
Replacing "lable" with "label".
=> Fix "lableName" typo.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Remove not needed operator==() and operator!=() on *FlagBits

README.md, VulkanHppGenerator.cpp, tests/StructureChain/StructureChain.cpp, vulkan/vulkan.hpp
=> Introduce functions vk::StructureChain::unlink<ClassType>() and vk::StructureChain::relink<ClassType>().

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/utils/utils.cpp, vulkan/vulkan.hpp
and simplify default values for constructor arguments
=> Introduce default initializers for member variables

VulkanHppGenerator.cpp, samples/RayTracing/CameraManipulator.hpp, tests/DispatchLoaderDynamic/DispatchLoaderDynamic.cpp, vulkan/vulkan.hpp
=> Add specific initialization of Flags and FlagBits.

VulkanHppGenerator.cpp, samples/RayTracing/CameraManipulator.hpp, vulkan/vulkan.hpp
Flags always default to just no FlagBits set.
=> Remove template parameter defaultValue from Flags.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Change return of StructureChain::get() from tuple of values to tuple of references

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Change init functions of DispatchLoaderDynamic to use a DynamicLoader specified by a template argument.

VulkanHppGenerator.cpp, tests/DeviceFunctions/DeviceFunctions.cpp, tests/DispatchLoaderDynamic/DispatchLoaderDynamic.cpp, tests/NoExceptions/NoExceptions.cpp, tests/StructureChain/StructureChain.cpp, tests/UniqueHandleDefaultArguments/UniqueHandleDefaultArguments.cpp, vulkan/vulkan.hpp
=> Resolve warnings from gcc.

VulkanHppGenerator.cpp, tests/ArrayCopy/ArrayCopy.cpp, tests/ArrayCopy/CMakeLists.txt, vulkan/vulkan.hpp
+ introduce new test ArrayCopy
=> Correct ConstExpression2DArrayCopy

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Simple addition, does what it says on the tin.
Apologies for the second request, somehow global .gitconfig got reset with work email instead of personal.
=> Add const versions of StructureChain::get

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
+ replace variables/struct members named "requires" with "requirements"
Resolves #515
=> Introduce spaceship operator<=>() with C++20, replacing all relational operators

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
+ add support of structExtends via alias'ed structures
+ add support of alias'ed commands via already alias'ed commands
=> Introduce support of VkFlags64

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Update of vk.xml to version 134; resolve warnings

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Improve handling of disabled extensions.

.travis.yml
This PR fixes recent failing clang builds for Travis-CI.
=> Fix broken Travis-CI builds for clang

README.md, VulkanHppGenerator.cpp, samples/utils/utils.cpp, vulkan/vulkan.hpp
=> Update to and adjustments for VK_HEADER_VERSION 136.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/Hash/CMakeLists.txt, tests/Hash/Hash.cpp, vulkan/vulkan.hpp
=> Provide std::hash<vk::HandleType> to make handles hashable.

VulkanHppGenerator.cpp, tests/ArrayProxy/ArrayProxy.cpp, tests/ArrayProxy/CMakeLists.txt, vulkan/vulkan.hpp
=> Refactor ArrayProxy and introduce test project on ArrayProxy

VulkanHppGenerator.cpp
=> Adjustments for VK_HEADER_VERSION 138.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
=> Adjust structure and union constructors and setter functions to correctly handle sType of a member of that structure/union.

VulkanHppGenerator.cpp
=> Make compound assignment operators on Flags<> constexpr with C++14.

CMakeLists.txt
=> Add version check for clang-format.

VulkanHppGenerator.cpp
=> Reintroduce ArrayProxy constructors with std::array and std::vector

VulkanHppGenerator.cpp
=> Change library name to load on linux to "libvulkan.so.1".

VulkanHppGenerator.cpp
=> Extend DynamicLoader loading policy

VulkanHppGenerator.cpp
=> Add some workarounds to not include windows.h on _WIN32 platform.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Improve extension protection string handling.

VulkanHppGenerator.cpp, tests/ResultValue/CMakeLists.txt, tests/ResultValue/ResultValue.cpp
=> Add cast operator to reference of UniqueHandle of ResultValue<UniqueHandle>

VulkanHppGenerator.cpp, tests/DeviceFunctions/DeviceFunctions.cpp
=> Provide default arguments in ObjectFree constructor for allocationCallbacks and dispatcher.

README.md, VulkanHppGenerator.cpp, tests/DispatchLoaderDynamicSharedLibrary/CMakeLists.txt, tests/DispatchLoaderDynamicSharedLibrary/DispatchLoaderDynamicSharedLibrary.cpp, tests/DispatchLoaderDynamicSharedLibraryClient/CMakeLists.txt, tests/DispatchLoaderDynamicSharedLibraryClient/DispatchLoaderDynamicSharedLibraryClient.cpp
=> Add defines to put the storage for a DispatchLoaderDynamic in a DLL.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Introduce helper class ArrayProxyNoTemporaries and structure setter functions using that.

VulkanHppGenerator.cpp
=> Guard use of ArrayProxyNoTemporaries with structure setter functions

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
Replace it by handling of structure members with a "values" attribute with a single element.
=> Remove (most of) the special handling of structure members named "sType"

VulkanHppGenerator.cpp
=> Simplify determination of returnParameterIndex

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
-> no need to forward declare the structures any more
=> Reordered listing of structures and handles

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> [DispatchLoaderDynamic] get aliases of functions if getting the function pointer failed

VulkanHppGenerator.cpp
+ new type trait isVulkanHandleType<>
Resolves #713
=> Introduce mapping between DebugReportObjectType enum value and the corresponding cpp handle type.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
+ mark wrong version as deprecated (C++14)
=> Correct version of two-step function returning two vectors of data

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
+ add missing array sizes for parameters
=> correct value-check of parameters

VulkanHppGenerator.cpp
+ Turn warning on never used VkStructureType enum value into an error.
=> Update to VK_HEADER_VERSION 157

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Refactor commands handling pointers to alien data types

CMakeLists.txt
=> Fix broken registry path usage

VulkanHppGenerator.cpp
=> Introduce helper function toHexString used in to_string functions on invalid values.

VulkanHppGenerator.cpp, tests/StructureChain/StructureChain.cpp
=> Add missing const-qualifier in the static_cast in function T const & StructureChain::getFeatures2() const.

VulkanHppGenerator.cpp
=> Replace check on (deprecated) VkDebugReportObjectTypeEXT enum values with check on VkObjectType values.

.appveyor.yml, VulkanHppGenerator.cpp
+ changed two now outdated warnings into error checks
=> Update to VK_HEADER_VERSION 161.

.appveyor.yml, samples/PhysicalDeviceMemoryProperties/CMakeLists.txt
+ remove breaking project samples/PhysicalDeviceMemoryProperties for MSVC
=> Add MSVC 2019 builds again

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
+ remove an obsolete assertion
=> Hold structure member attribute "optional" as a vector of bool.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Special handling for detecting mutual exclusive len usage on structures.

README.md, VulkanHppGenerator.cpp
=> Introduce configuration flag VULKAN_HPP_FLAGS_MASK_TYPE_AS_PUBLIC.

CMakeLists.txt, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/13_InitVertexBuffer/13_InitVertexBuffer.cpp, samples/15_DrawCube/15_DrawCube.cpp, samples/DrawTexturedCube/DrawTexturedCube.cpp, samples/DynamicUniform/DynamicUniform.cpp, samples/ImmutableSampler/ImmutableSampler.cpp, samples/InstanceExtensionProperties/InstanceExtensionProperties.cpp, samples/InstanceLayerExtensionProperties/InstanceLayerExtensionProperties.cpp, samples/InstanceLayerProperties/InstanceLayerProperties.cpp, samples/InstanceVersion/InstanceVersion.cpp, samples/MultipleSets/MultipleSets.cpp, samples/OcclusionQuery/OcclusionQuery.cpp, samples/PipelineCache/PipelineCache.cpp, samples/PipelineDerivative/PipelineDerivative.cpp, samples/PushConstants/PushConstants.cpp, samples/PushDescriptors/PushDescriptors.cpp, samples/RayTracing/CameraManipulator.hpp, samples/RayTracing/RayTracing.cpp, samples/SeparateImageSampler/SeparateImageSampler.cpp, samples/Template/Template.cpp, samples/utils/math.hpp, tests/ArrayProxy/ArrayProxy.cpp, tests/DesignatedInitializers/DesignatedInitializers.cpp
=> Fix compiler warnings on gcc/clang

VulkanHppGenerator.cpp, tests/StructureChain/StructureChain.cpp
=> Introduce new function StructureChain::isLinked<>()

VulkanHppGenerator.cpp, tests/StructureChain/StructureChain.cpp
=> Fix function StructureChain::unlink().

samples/utils/utils.cpp
Still disabled by default due to yet to be resolved issues.
=> Prepare usage of BestPractices validation layer.

README.md
=> Mention connection of VULKAN_HPP_STORAGE_API and VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE in the README.md

README.md
=> Correct documentation on DispatchLoaderDynamic

VulkanHppGenerator.cpp
Hi,
This PR adds support for QNX platform.
Thanks!
=> Add support for QNX.

VulkanHppGenerator.cpp
+ improved formatting of bitmasks and enums
=> Introduce support of "encode" and "decode" for attribute <queues> of a command

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Add missing VULKAN_HPP_INLINE to function definitions

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
This is to fix https://github.com/KhronosGroup/Vulkan-Hpp/issues/902
=> Fix enum array initializer using enum constant

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Add assertion on valid function pointer for functions depending on extensions.

tests/DesignatedInitializers/DesignatedInitializers.cpp
=> Extend test on designated initializers

VulkanHppGenerator.cpp
=> Add "type" as an optional attribute for enums.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Add support for functions with a new parameter pattern.

VulkanHppGenerator.cpp
=> Add missing ResultValue<std::vector<UniqueHandle<Type, Dispatch>>>::asTuple()

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
All those values erroneously started with "e2", instead of just "e".
=> Correct enum values for AccessFlagBits2KHR and PipelineStageFlagBits2KHR.

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Introduce vk::raii::InstanceDispatcher and vk::raii::DeviceDispatcher

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Turn an assertion on identifying a command into a check.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkan_raii.hpp
Keeps the relative position of other members constant when compiling for different platforms.
=> Add placeholder members to Dispatchers

VulkanHppGenerator.cpp, tests/ArrayProxy/ArrayProxy.cpp, vulkan/vulkan.hpp
=> Introduce constructors of ArrayProxy from std::span (C++20)

VulkanHppGenerator.cpp
=> Use "altlen" attribute instead of "len", if present.

VulkanHppGenerator.cpp
=> Resolve two release build issues.

VulkanHppGenerator.cpp
=> Fix extension name used to check consistency of enum values.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Change 32-bit test in ArrayWrapper1D to using VK_USE_64_BIT_PTR_DEFINES.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp
=> Add support of functions taking and returning a vector of data

RAII_Samples/06_InitDepthBuffer/06_InitDepthBuffer.cpp, RAII_Samples/10_InitRenderPass/10_InitRenderPass.cpp, RAII_Samples/12_InitFrameBuffers/12_InitFrameBuffers.cpp, RAII_Samples/13_InitVertexBuffer/13_InitVertexBuffer.cpp, RAII_Samples/14_InitPipeline/14_InitPipeline.cpp, RAII_Samples/15_DrawCube/15_DrawCube.cpp, RAII_Samples/CopyBlitImage/CopyBlitImage.cpp, RAII_Samples/DrawTexturedCube/DrawTexturedCube.cpp, RAII_Samples/DynamicUniform/DynamicUniform.cpp, RAII_Samples/ImmutableSampler/ImmutableSampler.cpp, RAII_Samples/InitTexture/InitTexture.cpp, RAII_Samples/InputAttachment/InputAttachment.cpp, RAII_Samples/MultipleSets/MultipleSets.cpp, RAII_Samples/OcclusionQuery/OcclusionQuery.cpp, RAII_Samples/PipelineCache/PipelineCache.cpp, RAII_Samples/PipelineDerivative/PipelineDerivative.cpp, RAII_Samples/PushConstants/PushConstants.cpp, RAII_Samples/PushDescriptors/PushDescriptors.cpp, RAII_Samples/RayTracing/RayTracing.cpp, RAII_Samples/SecondaryCommandBuffer/SecondaryCommandBuffer.cpp, RAII_Samples/SeparateImageSampler/SeparateImageSampler.cpp, RAII_Samples/SurfaceCapabilities/SurfaceCapabilities.cpp, RAII_Samples/SurfaceFormats/SurfaceFormats.cpp, RAII_Samples/Template/Template.cpp, RAII_Samples/TexelBuffer/TexelBuffer.cpp, RAII_Samples/utils/utils.hpp, README.md, VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkan_raii.hpp
=> Introduce constructors on nullptr_t for the RAII handle classes.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
=> Remove dumb parent-pointer in raii-objects.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp
+ slightly reordered error handling in enumerating functions.
=> Add support of functions enumerating chained structure data.

VulkanHppGenerator.cpp, vulkan/vulkan_structs.hpp
+ correctly format vulkan_structs.hpp
=> Fix allocator name in generateCommandResultEnumerateChained()

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix wrong linking in copied StructureChains with unlinked elements

VulkanHppGenerator.cpp
=> Downgrade <formats> tag from required to optional.

VulkanHppGenerator.cpp
Commands returning void, that are supposed to enumerate one vector of data is generalized to also support void-data by a templated type.
=> Generalize command generation for a specific type of commands

RAII_Samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, RAII_Samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/utils/utils.cpp
=> Change type of loop variables from uint8_t to uint32_t.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
First part of resolving issue #1202.
=> Introduce member function swap() for raii-classes.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
=> Introduce member function clear() for raii-classes.

tests/FormatTraits/CMakeLists.txt, tests/FormatTraits/FormatTraits.cpp
=> Make test/FormatTraits.cpp valid for C++11.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp
Generation of functions that return a VkResult and either get some data or not are combined into one function.
+ some minor cleanup
=> Combine two types of commands into one generation function.

VulkanHppGenerator.cpp
=> Add some error handling for a std::system call.

RAII_Samples/RayTracing/RayTracing.cpp, RAII_Samples/utils/utils.hpp, VulkanHppGenerator.cpp, samples/PhysicalDeviceGroups/PhysicalDeviceGroups.cpp, samples/RayTracing/RayTracing.cpp, samples/utils/utils.cpp
=> Add pNext as optional last argument to constructors of structs that hold a pNext.

VulkanHppGenerator.cpp, tests/UniqueHandle/CMakeLists.txt, tests/UniqueHandle/UniqueHandle.cpp, vulkan/vulkan.hpp
+ add test project for UniqueHandles.
Resolves #1268.
=> Re-add accidentally removed version of createResultValue

VulkanHppGenerator.cpp, tests/UniqueHandle/UniqueHandle.cpp, vulkan/vulkan.hpp
=> Add missing allocator template argument in createResultValue helper functions working on std::vector<UniqueHandle> types.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
Should resolve at least part of #1315.
=> Remove spaceship operator for structures containing function pointers

VulkanHppGenerator.cpp, vulkan/vulkan_enums.hpp
=> Revert struct conversion operators to be implicit.

CMakeLists.txt
=> Make the samples' precompiled headers reuse that from the utils project.

snippets/includes.hpp, vulkan/vulkan.hpp
=> Unconditionally include <algorithm> in vulkan.hpp.

RAII_Samples/05_InitSwapchain/05_InitSwapchain.cpp, RAII_Samples/utils/utils.hpp, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
+ some minor cleanup
Resolves #1412.
=> Fix inconsistency with return type of vk::raii::SwapchainKHR::getImages()

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_enums.hpp
=> Cleanup on protection handling

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkan_enums.hpp
=> Remove outdated conditions around two init functions of the DispatchLoaderDynamic.

.clang-format_11, .clang-format_12, .clang-format_13, .clang-format_14, .clang-format_7
=> Change argument for format option "SpacesInAngles" from "Never" to "false"

.github/workflows/update-header-pr.yml
https://github.com/theHamsta/Vulkan-Hpp/actions/runs/3984992043/jobs/6831831633
=> ci: fix failing clang-format-15 via apt.llvm.org

.github/workflows/update-header-pr.yml
This time the workflow run successfully https://github.com/theHamsta/Vulkan-Hpp/actions/runs/3986137677/jobs/6834352682
=> ci: fix usage of tee to add llvm-snapshot

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Add support for filtering out vulkansc stuff.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
=> Change requiredIn in TypeData from std::string to std::set<std::string>

VulkanHppGenerator.cpp
=> Fix handling of multiple vs. single success codes on handle creation with vulkan_raii.hpp.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/ExtensionInspection/CMakeLists.txt, tests/ExtensionInspection/ExtensionInspection.cpp, vulkan/vulkan_extension_inspection.hpp, vulkan/vulkansc_extension_inspection.hpp
plus renamed some of the previous extension inspection functions
=> Introduce extension inspection functions get[Device|Instance|Deprecated|Promoted|Obsoleted]Extension;

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/ExtensionInspection/ExtensionInspection.cpp, vulkan/vulkan_extension_inspection.hpp, vulkan/vulkansc_extension_inspection.hpp
Note: uses a mapping from some complex depends strings to a canonical form.
=> Introduce extension inspection function vk::getExtensionDepends.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_funcs.hpp, vulkan/vulkansc_handles.hpp, vulkan/vulkansc_raii.hpp
+ refactor returnType generation
=> Add support for a new class of functions

snippets/ObjectDestroy.hpp, snippets/ObjectFree.hpp, snippets/ObjectRelease.hpp, snippets/PoolFree.hpp
=> Expose the dispatch member of deleters

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
That sub-tree on `<sync>` is just parsed and some checks are done.
=> Add support for new element <sync> in vk.xml

snippets/defines.hpp, vulkan/vulkan.hpp
=> Undef True/False in case they are defined and introduce some constexpr True/False to replace them.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Introduce hard-coded default values for some structure members.

VideoHppGenerator.cpp, VulkanHppGenerator.cpp, XMLHelper.hpp, vulkan/vulkan.cppm, vulkan/vulkan.hpp, vulkan/vulkan_enums.hpp, vulkan/vulkan_extension_inspection.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_hash.hpp, vulkan/vulkan_static_assertions.hpp, vulkan/vulkan_to_string.hpp, vulkan/vulkan_video.hpp, vulkan/vulkansc.hpp, vulkan/vulkansc_enums.hpp, vulkan/vulkansc_to_string.hpp
Reverts KhronosGroup/Vulkan-Hpp#1661
=> Revert "Update Vulkan-Headers to v1.3.265"

VulkanHppGenerator.cpp, vulkan/vulkan.cppm, vulkan/vulkan_handles.hpp, vulkan/vulkan_shared.hpp, vulkan/vulkansc.cppm, vulkan/vulkansc_handles.hpp, vulkan/vulkansc_shared.hpp
=> Identify delete commands starting with "vkRelease"

samples/utils/shaders.cpp, snippets/ArrayWrapper1D.hpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Update submodule glslang to version 13.0.0

tests/ArrayProxy/ArrayProxy.cpp, tests/ArrayProxyNoTemporaries/ArrayProxyNoTemporaries.cpp, tests/ArrayWrapper/ArrayWrapper.cpp, tests/UniqueHandle/UniqueHandle.cpp
=> Ignore warnings in some tests; fix ambiguity in ArrayWrapper test

VideoHppGenerator.cpp, vulkan/vulkan_video.hpp
=> Add missing include guard to vulkan_video.hpp

snippets/ArrayWrapper1D.hpp, snippets/includes.hpp, tests/ArrayWrapper/ArrayWrapper.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Fix ArrayWrapper1D::operator std::string() and ArrayWrapper1D::operator std::string_view() to return a string/string_view of the correct length.

README.md
=> Update readme on using vulkan-headers instead of vulkan-hpp with vcpkg.

snippets/macros.hpp, vulkan/vulkan_hpp_macros.hpp, vulkan/vulkansc_hpp_macros.hpp
=> Include headers holding feature-test macros in vulkan_hpp_macros.hpp.

.github/workflows/ci-windows.yml
=> Reduce number of jobs in CI by running a loop in a job

VulkanHppGenerator.cpp, XMLHelper.hpp
=> Add support of attribute "len" for array-sized structure members.

VulkanHppGenerator.cpp
=> Add support for command argument attribute "len" with value "1".

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_funcs.hpp
Changed return type from `ResultValue` to `ResultValueType`
=> Special handling for command vkGetDeviceFaultInfoEXT

VulkanHppGenerator.cpp, tests/CppType/CppType.cpp, vulkan/vulkan_handles.hpp, vulkan/vulkansc_handles.hpp
=> Guard type trait CppType to map from VkHandle to vk::Handle by ( VK_USE_64_BIT_PTR_DEFINES == 1 ).

VulkanHppGenerator.cpp, vulkan/vulkansc_structs.hpp
=> Change member initialization lists of structs to use braces {} instead of parentheses ()

snippets/ArrayWrapper1D.hpp, tests/ArrayWrapper/ArrayWrapper.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Improve relational operators on ArrayWrapper1D.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_enums.hpp, vulkan/vulkansc_enums.hpp
=> Introduce some special handlings for structure VkLayerSettingEXT.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Remove deprecation message on promoted extensions.

VulkanHppGenerator.cpp, vulkan/vulkan_enums.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkansc_enums.hpp, vulkan/vulkansc_funcs.hpp, vulkan/vulkansc_handles.hpp, vulkan/vulkansc_structs.hpp
=> Add IWYU pragmas to let code-completers use vulkan.hpp.

README.md
=> Add some docu on vk::raii classes

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Extend cases when vk::detail::DispatchLoaderStatic is defined.

VulkanHppGenerator.cpp, vulkan/vulkan_handles.hpp
=> Re-add compare operators of vk-handles, needed for 32bit builds.

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
=> Export detail::getDispatchLoaderStatic in vulkan.cppm

VulkanHppGenerator.cpp, vulkan/vulkan_handles.hpp
=> Adjust namespace of compare operators on vk-handles.

CMakeLists.txt, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, XMLHelper.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp
=> Parallelize the generation of the files.

README.md
=> Update namespace usage of DispatchLoaderDynamic, DispatchLoaderStatic and DynamicLoader in the readme.

.clang-format_14, VulkanHppGenerator.cpp, XMLHelper.hpp
=> Throw on clang_format failure; fix comment

VulkanHppGenerator.cpp, snippets/CppModuleFileTemplate.hpp, snippets/HandlesTemplate.hpp, snippets/ObjectDestroy.hpp, snippets/defines.hpp, vulkan/vulkan.cppm, vulkan/vulkan.hpp, vulkan/vulkan_enums.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_hash.hpp, vulkan/vulkan_raii.hpp
=> Replace some more "vk::" by "VULKAN_HPP_NAMESPACE::"

samples/CopyBlitImage/CopyBlitImage.cpp, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp
These samples do not draw a cube.
=> Fixed commenting

CMakeLists.txt, RAII_Samples/CMakeLists.txt, samples/CMakeLists.txt
=> Adjust build files to allow test builds without sample builds

VulkanHppGenerator.cpp
Also fixes generation of structures used in a structure
=> Fix correctness checks for syncaccess and syncstage

snippets/macros.hpp, vulkan/vulkan_hpp_macros.hpp
=> Check language feature macro for existence before using it

snippets/includes.hpp, vulkan/vulkan.hpp
Additionally, cleaned up conditional inclusions.
Resolves #2132
=> Include cassert unconditionally

VulkanHppGenerator.cpp
- Add two new structures to the multipleLenStructs list
Change-Id: I5fea56734eced9c96dd5bbcc4057d72260497969
=> Add support for VK_ARM_tensors

VulkanHppGenerator.cpp, vulkan/vulkan_enums.hpp
=> Include missing header type_traits to vulkan_enums.hpp

README.md
=> Add a table of contents to the README.md

VulkanHppGenerator.cpp, snippets/Exceptions.hpp, snippets/ObjectDestroy.hpp, snippets/ResultValue.hpp, snippets/resultChecks.hpp, vulkan/vulkan.hpp
=> Remove redundant occurrences of VULKAN_HPP_NAMESPACE:: in vulkan.hpp.

VulkanHppGenerator.cpp, vulkan/vulkan_enums.hpp
=> Remove redundant occurrences of VULKAN_HPP_NAMESPACE:: in vulkan_enums.hpp.

VulkanHppGenerator.cpp, snippets/HandlesTemplate.hpp, vulkan/vulkan_handles.hpp
=> Remove redundant occurrences of VULKAN_HPP_NAMESPACE:: in vulkan_handles.hpp

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, snippets/RAIIHppFileTemplate.hpp, snippets/ResultValue.hpp, snippets/macros.hpp, tests/NoExceptionsRAII/CMakeLists.txt, tests/NoExceptionsRAII/NoExceptionsRAII.cpp, vulkan/vulkan.hpp, vulkan/vulkan_hpp_macros.hpp, vulkan/vulkan_raii.hpp
=> Extend support of VULKAN_HPP_NO_EXCEPTIONS in the raii-namespace

VulkanHppGenerator.cpp, snippets/HandlesTemplate.hpp, vulkan/vulkan_handles.hpp
=> Remove the superfluous operator<=> for handles.

README.md, vk_raii_ProgrammingGuide.md
=> Start of breaking changes documentation
