KhronosGroup/Vulkan-Hpp

README.md
There are two reasons for this change.
1. The C++ mantra "throw by value, catch by reference" still applies,
even when you're only specifically throwing std::system_error at this
time
2. Vulkan-Hpp is using C++ stdlib containers, such as std::string and
std::vector, which have their own exception specifications to consider.
The example provided may throw various exceptions, all of which derive
from std::exception, and many will not be std::system_error.
This is a serious issue in the readme simply because that snippet of
code will be the copy/pasted foundation of many projects which adopt
Vulkan-Hpp. We might as well try to avoid some common pitfalls of
exception handling.
=> Change readme example to catch std::exception

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
The constructor that initializes from the `BitType` should probably cast its `bit` argument to `MaskType` (which may or may not be synonymous with `uint32_t`), which is the type of the `m_mask` member that's being initialized.
=> Cast to MaskType rather than uint32_t

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
This allows developers to write
vk::Result result;
vk::Image image;
std::tie(result, image) = device.createImage(...);
when using the non-exception mode.
=> Add support for std::tie on ResultValues. 

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
MSVC didn't inline some of the critical functions like createResult. Due to this all occurrences of inline now have been replaced by VULKAN_HPP_INLINE which gives the compiler a stronger inlining hit.
=> Add VULKAN_HPP_INLINE to force inlining 

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
in addition to RefType& and nullptr. This is required since *nullptr is illegal and writing (ptr == nullptr) ? nullptr : *ptr isn't an efficient solution for the problem.
=> Add constructor to Optional<RefType> which accepts a RefType*

README.md, vulkan/vulkan.hpp
=> Fix naming conventions for functions in README.md and update to Vulkan 1.0.34

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
- add some forward declaration support to resolve (direct) circular dependencies
- check on multiple output arguments of functions, using none then
- add "protect" support on handles
- correct type determination on "const Type* const*"
=> Update to rel 1.0.35

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
- CommandData now holds it's full function name (without "vk") and it's reduced function name (used as member function name);
- CommandData now holds the name of the owning handle (class), if it is owned by one;
- EnumData now holds the name of that enum;
- for consistency reasons, "Arguments" have been renamed to "Params"
- some functions have been changed to output to std::ostream (instead of std::ofstream), to detect and filter equal function bodies for enhanced/non-enhanced mode;
- changed some functions to use std::algorithms and lambdas instead of explicit loops
=> Cleanup on data structures and more:

README.md
An extra back-tick on line 146 caused markdown to mess up after that point.
My editor also removed a bunch of extraneous white-space.
=> Removed extra back tick.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Base exception architecture:
* vk::Error
** vk::LogicError : std::logic_error
** vk::SystemError : std::system_error
*** vk::$ErrorResultEnumName$Error : SystemError
This is to have backward compatibility with existing code which was catching std::logic_error or std::system_error.
=> Introduce custom exceptions for Vulkan-Hpp (#97)

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
- Add `Type * operator->()`
- Fix `Type get() const` to `const Type & get() const`
- Add `Type & get()`
Fixes https://github.com/KhronosGroup/Vulkan-Hpp/issues/122#issuecomment-327198391
=> Add UniqueHandle non-const accessors, ensure all by reference.

README.md
Show Travis-CI build status in the README.md so that it is easily seen while viewing the GitHub repo.
Feel free to move it elsewhere in the file as you see fit.  (But near the top is nice :-) )
=> Add Travis-CI badge to README.md

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
There're cases where vendors are non-standard conform and return positive return codes and it's also possible that new success codes could be introduced which require special handling. For the latter case it's legit to throw an exception which a positive result code.
=> Fix issue #147. Do not assert on negative result codes when throwing an exception

README.md
- Fix indentation of titles.
- Fix usage of code fences.
- Add missing code fences.
- Add missing language declarations.
- Move project description above header.
- Fix some minor typos.
- Add See Also (fixes #112)
- Add inline license according to LICENSE.txt.
=> Tidy up README.md, add "See Also" and "License".

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
It's often useful to browse through vulkan.hpp to check what the default values
for various info structs are, but having them on a single line makes it hard to
read.
This change puts each ctor argument on a different line, which makes the
default values more visible.
=> List out default ctor parameters in separate lines

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Resolves issue #233
ObjectDestroy, ObjectFree and PoolFree currently store a const reference to the Dispatch objects which inhibits the compiler from generating copy/move operators and a move constructor.
=> Changed m_dispatch to pointer type to fix copy/move of UniqueHandles

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
> Fix for issue https://github.com/KhronosGroup/Vulkan-Hpp/issues/272
Use move semantics when calling `createResultValue` to allow compiling when `T` is a `std::vector<UniqueHandle<>>`.
=> Use std::move when calling createResultValue with NO_EXCEPTIONS

VulkanHppGenerator.cpp
At the moment, pulling out individual components of a structure chain involves multiple calls to `get` and creating references to each individual element in the chain:
```cpp
// Makes a structure-chain type
auto DevicePropertyChain
= SomePhysicalDevice.getProperties2<
vk::PhysicalDeviceProperties2,
vk::PhysicalDeviceIDProperties
>();
// Now I have to pull out individual references
auto& DeviceProperties = DevicePropertyChain.get<vk::PhysicalDeviceProperties2>();
auto& DeviceIDProperties = DevicePropertyChain.get<vk::PhysicalDeviceIDProperties>();
```
A tuple-based accessor is added that returns a tuple of the requested reference types. Also allows for [structured-binding](https://en.cppreference.com/w/cpp/language/structured_binding) based declarations.
```cpp
// Makes a structure-chain …
```
=> Add StructureChain tuple-based accessor

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
- Extend and unify alias handling on feature and extension enums
- Extend aliases of enums handling to accept two levels of aliasing
- Extend aliases of structures to allow mulitple aliases of the same structure
- Simplify forward declarations to just declare all structures and aliases
=> Improve alias handling of enums and structs:

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
In the same spirit of `std::unique_ptr::element_type`--want to be able to easily retrieve the type of the class managed by the UniqueHandle.
=> Add type alias for underlying type of vk::UniqueHandle

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
Some third-party libraries includes `vulkan.h` with `VK_NO_PROTOTYPES` defined (e.g. Qt).
Currently, to use Vulkan-Hpp with these libraries you need to include the Vulkan and certain Qt headers in the correct order.
This patch avoids this hassle by supporting compilation with VK_NO_PROTOTYPES defined.
This works by adding checks for `VK_NO_PROTOTYPES` and disables code that relies on the prototypes:
`DispatchLoaderStatic` and certain initializations of `DispatchLoader`.
This also means that you _need_ to manually provide a Dispatcher (`DispatchLoaderDynamic` or somethinh custom) for all Vulkan-Hpp calls; but presumably you're using some kind of dynamic dispatching anyway if you haven't got the prototypes.
=> Support compilation with VK_NO_PROTOTYPES defined

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
This PR renames variables named `requires` to `requirement`, as `requires` will become a keyword in the upcoming c++20 standard.
This is a generator only problem and does not affect the resulting `vulkan.hpp` file.
=> Rename all variables named 'requires', which is a keyword in c++20

VulkanHppGenerator.cpp
This PR fixes an expression of the form
`os << someOptional ? x : y`, which should be
`os << (someOptional ? x : y)`.
Otherwise, it discards the result of the inline if due to the higher precedence of the `<<` operator.
While this change could technically change the resulting `vulkan.hpp`, it does in fact not change the current one, as the the faulty path is apparently not taken for the latest xml spec.
=> Corrected inline if, which should be evaluated before writing output

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Fixes compilation issues on 32-bit platforms (or where `VULKAN_HPP_TYPESAFE_CONVERSION` is not defined).
See: #343
=> Add explicit casts to DispatchLoaderDynamic::init(vk::Instance const&, vk::Device const&)

VulkanHppGenerator.cpp
It's the VK_ANDROID_native_buffer extension, which is a vendor extension hidden in between Vulkan loader and the ICD, so it's marked disabled.
Below are the enums causing header generation failures that were added in some later version of this extension:
```
typedef enum VkSwapchainImageUsageFlagBitsANDROID {
VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID = 0x00000001,
VK_SWAPCHAIN_IMAGE_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkSwapchainImageUsageFlagBitsANDROID;
typedef VkFlags VkSwapchainImageUsageFlagsANDROID;
```
```xml
<extension name="VK_ANDROID_native_buffer" number="11" type="device" author="ANDROID" platform="android" contact="Jesse Hall @critsec" supported="disabled">                                                    
<require>
<comment>VK_ANDROID_native_buffer is used between …
```
=> Fix the header generation for complex disabled extensions

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
- make layout-structure default constructor an empty function
- introduce default constructor for the corresponding (non-layout) structure, delegating to the layout-structure's constructor
- introduce copy- and assignment constructors from the corresponding vulkan-structure, delegating to the copy- and assignment constructor from the layout-structure
Resolves #380.
=> Resolve instantiation issue with structures that are flagged as returnedonly

VulkanHppGenerator.cpp, samples/01_InitInstance/CMakeLists.txt, samples/16_Vulkan_1_1/16_Vulkan_1_1.cpp, samples/CMakeLists.txt, samples/CreateDebugUtilsMessenger/CMakeLists.txt, samples/EnableValidationWithCallback/CMakeLists.txt, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/InstanceExtensionProperties/CMakeLists.txt, samples/InstanceLayerExtensionProperties/CMakeLists.txt, samples/InstanceLayerProperties/CMakeLists.txt, samples/PushDescriptors/PushDescriptors.cpp, samples/RayTracing/RayTracing.cpp, samples/utils/utils.cpp, vulkan/vulkan.hpp
The utility function vk::su::createInstance either creates a default DispatchLoaderDynamic, or prepares usage of DebugUtilsMessenger with a DispatchLoaderStatic as the default.
=> Change (most of) the samples to use the DispatchLoaderDynamic by default

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Make ConstExpressionArrayCopy::copy() a constexpr with C++14 earliest.

VulkanHppGenerator.cpp
Added MacOS specific code to the DynamicLoader class.
vkCubepp in KhronosGroup/Vulkan-Tools requires this change to
build on MacOS.
=> build: Add MacOS Specific Code to DynamicLoader

samples/InstanceLayerProperties/InstanceLayerProperties.cpp, samples/InstanceVersion/CMakeLists.txt, samples/InstanceVersion/InstanceVersion.cpp, samples/PhysicalDeviceExtensions/CMakeLists.txt, samples/PhysicalDeviceExtensions/PhysicalDeviceExtensions.cpp, samples/PhysicalDeviceFeatures/CMakeLists.txt, samples/PhysicalDeviceFeatures/PhysicalDeviceFeatures.cpp, samples/PhysicalDeviceGroups/CMakeLists.txt, samples/PhysicalDeviceGroups/PhysicalDeviceGroups.cpp, samples/PhysicalDeviceMemoryProperties/CMakeLists.txt, samples/PhysicalDeviceMemoryProperties/PhysicalDeviceMemoryProperties.cpp, samples/PhysicalDeviceProperties/CMakeLists.txt, samples/PhysicalDeviceProperties/PhysicalDeviceProperties.cpp, samples/PhysicalDeviceQueueFamilyProperties/CMakeLists.txt, samples/PhysicalDeviceQueueFamilyProperties/PhysicalDeviceQueueFamilyProperties.cpp, samples/RayTracing/RayTracing.cpp, samples/SurfaceCapabilities/CMakeLists.txt, samples/SurfaceCapabilities/SurfaceCapabilities.cpp, samples/SurfaceFormats/CMakeLists.txt, samples/SurfaceFormats/SurfaceFormats.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp
new:
- InstanceVersion: print out the instance version
- PhysicalDeviceExtensions: print out the device specific extensions
- PhysicalDeviceFeatures: print out the device specific features
- PhysicalDeviceGroups: print out the device groups (interesting with SLI)
- PhysicalDeviceMemoryProperties: print out the device specific memory properties
- PhysicalDeviceQueueFamilyProperties: print out the device specific queue family properties
- SurfaceCapabilities: print out the surface specific capabilities
- SurfaceFormats: print out the supported surface specific formats
improved:
- InstanceExtensionProperties: print out the instance extensions alphabetically
- InstanceLayerProperties: removed an unused local function
- RayTracing: improved fence usage
=> Add a couple of new samples, improved some others:

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
When you use `vk::ArrayProxy` with C++17 Class Template Argument Deduction(CTAD), template parameter `T` always deduced into argument type of constructor because `ArrayProxy(T & ptr)` always produces best match than other constructors for `std::array` or `std::vector`.  
```cpp
std::array<int, 42> array;
vk::ArrayProxy prox = array;  // vk::ArrayProxy<std::array<int, 42>>
prox.size(); // 1!
```
This is very counter-intuitive and potentially becomes a source of nasty bugs.  
This PR disables CTAD on `ArrayProxy(T &)` by changing it to `ArrayProxy(typename std::remove_reference<T>::type &)` so compilers no longer be able to deduce `T` from argument.  
I'll probably do the same on `ArrayProxy(std::initializer_list<T> const&)` too.
In the future, we can add deduction guides to enable CTAD …
=> Disable CTAD on ArrayProxy's constructors

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
I wasn't really sure what to do with this. Windows is just annoying to work with, and I just hit this on a test project at work.
The other solution is to just force calling `LoadLibraryA`. Both works, but I don't know which one is better, if any.
This macro is defined by `winnt.h`, so I don't see it getting removed anytime soon.
=> Implement support for unicode Windows projects using `vk::DynamicLoader`.

CMakeLists.txt
This CL adds the VULKAN_HPP_RUN_GENERATOR option which will run the
vulkan hpp generator from CMake if enabled.
=> Add CMakeList target to run generator

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Introduce default constructors for ObjectDestroy, ObjectFree, and UniqueHandle.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Fix ambiguous constructor of ObjectDestroy with vk::NoParent.

samples/utils/utils.cpp
vk::PipelineVertexInputStateCreateInfo::pVertexBindingDescriptions used to run out of scope before being used in the Device::createGraphicsPipelineUnique resulting in undefined behavior.
=> Fixed vertexBindingDescription scope.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Add is_error_code_enum only if VULKAN_HPP_NO_EXCEPTIONS is not defined.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
When a struct holds a fixed size array of stuff, and the member variable right before that array is the count (determined by its specific name) for that array, we now only compare that number of stuff.
Resolves #456
=> Improve operator==() of structs

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp
+ support for 2D arrays
+ support for bitfield members in a structure (slightly restricted: no default member initializers and for any vk::*FlagBits member Vk*FlagBits would be used)
+ aliases to enums are listed by using declarations
+ for aliases to handle types, an aliased Unique handle type is added by a using declaration
+ a check in determining an enhanced return type is extended
+ added operator=() for unions.
=> Added a couple of features:

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
It seems like the default `dispatch` argument should be `VULKAN_HPP_DEFAULT_DISPATCHER` rather than default constructing a new dispatcher.
Default constructing a new dispatcher probably works fine when using static dispatch, but fails with dynamic dispatch since the dynamic dispatcher uses a `VkInstance` (and a `VkDevice`) which the newly default constructed dispatcher lacks.
=> Fix regression in ObjectDestroy default argument

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
I also suggest to define `VULKAN_HPP_ASSERT` and use it in both `VulkanHppGenerator.cpp` and `VulkanHppGenerator.hpp`, regardless of whether it is generated code or not. It would be less error prone.
=> use VULKAN_HPP_ASSERT instead of raw assert in generated code

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
This avoids unintentional library closes or double-closes when handle is transferred via the default copy constructor.
=> Add move semantics to DynamicLoader

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Continuation of #508.
In case of move assign over already-opened DynamicLibrary, swapping the handle ensures the existing handle is closed.
=> Use std::swap for DynamicLibrary move assign

.appveyor.yml, CMakeLists.txt, samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/CMakeLists.txt, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/PhysicalDeviceGroups/PhysicalDeviceGroups.cpp, samples/RayTracing/RayTracing.cpp, samples/utils/CMakeLists.txt, samples/utils/utils.cpp, samples/utils/utils.hpp
This PR enables samples on AppVeyor builds.
Following configurations are included:
- Visual Studio images
+ `Visual Studio 2015`
+ `Visual Studio 2017`
+ `Visual Studio 2019`
- Arch options:
+ `Win32`
+ `x64`  
All builds are compiled with `Debug`.
=> Enable samples on AppVeyor builds

VulkanHppGenerator.cpp
=> Use [[deprecated]] only if __has_cpp_attribute(deprecated) is true

VulkanHppGenerator.cpp
=> Use attribute [[deprecated]] only if __cplusplus >= 201402L.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
- only members named <sType> are supposed to have a <values> attribute
- no <values> attribute is allowed to occur more than once.
=> Add checks on member sType of structs:

VulkanHppGenerator.cpp, tests/ResultValueRValue/CMakeLists.txt, tests/ResultValueRValue/ResultValueRValue.cpp
Allows objects returned as ResultValue (instead of ResultValueType::type) to be moved without requiring additional casting or explicit use of ResultValue::value.
Resolves #589
=> Provide rvalue cast operator for ResultValue

VulkanHppGenerator.cpp, tests/ResultValue/CMakeLists.txt, tests/ResultValue/ResultValue.cpp, tests/ResultValueRValue/ResultValueRValue.cpp
This PR adds missing ref-qualifiers to complete #590 , also adds sore more test cases.
Should fix #616
=> [HPP][ResultValue] Add missing ref-qualifier to conversion operators

VulkanHppGenerator.cpp
-> needed to add all the relational operators on <char,N> as well to keep the compiler happy!
Resolves #622.
=> Introduce cast-operator to std::string and std::string_view on ArrayWrapper1D<char,N>

VulkanHppGenerator.cpp
Fix build errors due to hardcoded namespace `vk::` when user defined `VULKAN_HPP_NAMESPACE` is used.
=> Replace hardcoded namesapce 'vk::' to 'VULKAN_HPP_NAMESPACE'.

VulkanHppGenerator.cpp
Fix a build error when `VULKAN_HPP_NO_SMART_HANDLE` is defined.
=> Fix if condition of result unique handle

README.md, VulkanHppGenerator.cpp
This PR adds `VULKAN_HPP_ASSERT_ON_RESULT` discussed in #644
=> Add VULKAN_HPP_ASSERT_ON_RESULT

VulkanHppGenerator.cpp, samples/InstanceLayerExtensionProperties/InstanceLayerExtensionProperties.cpp
This PR removes `const` on return type and `VULKAN_HPP_NOEXCEPT` from string conversion operators of `Array1DWrapper`.
Not sure this is intended, but it seems `const` and `VULKAN_HPP_NOEXCEPT` on these operators are not necessary, considering `const` prevents move semantics and both `std::string` and `std::string_view` can possibly throw on construction.
=> Small fix for ArrayWrapper1D's conversion operators

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/DeviceFunctions/DeviceFunctions.cpp
+ change the order of Allocator and Dispatch template arguments for functions returning a std::vector<UniqueStuff>, as the Allocator needs to use the Dispatch in those cases!
=> Extend template argument list for functions returning a std::vector<Stuff> to help compilers detecting the correct function.

VulkanHppGenerator.cpp
=> Additionally guard spaceship-operator by check for existence of std-header <compare>

README.md
Hello!
First of all, great work on Vulkan-Hpp and Vulkan. I am only beginning in the world of Vulkan and 3D rendering, which lead me to read the readme and try one code snippet in my IDE to test auto-completion.
The code snippet I copy/pasted have a few typos, I think. I only tried these two examples, which mean I haven't checked other examples.
I hope nothing is wrong in the code change I propose.
This PR is really low-priority!
Thank you for your great work.
=> Fix code typos in Readme

README.md, VulkanHppGenerator.cpp
=> Introduce VULKAN_HPP_NO_DEFAULT_DISPATCHER to not have a default argument for the last argument of each function.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/RayTracing/RayTracing.cpp, tests/DeviceFunctions/DeviceFunctions.cpp
- marked previous function that got an ArrayProxy as deprecated (C++14)
- introduce a new function returning a std::vector of the given size
- introduce a new function returning a single value
Resolves #727
=> Special handling for commands that get a size and a void-pointer to write data to

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/OcclusionQuery/OcclusionQuery.cpp
- mark wrong version as deprecated (C++14)
- introduce new version returning ResultValue<vector<T,Allocator>>
- introduce new singular version returning ResultValue<T>
=> correct enhanced version of vkGetQueryPoolResults

VulkanHppGenerator.cpp, samples/14_InitPipeline/14_InitPipeline.cpp
Allows coding like this:
vk::Result         result;
vk::UniquePipeline pipeline;
std::tie( result, pipeline ) =
device->createGraphicsPipelineUnique( nullptr, graphicsPipelineCreateInfo ).asTuple();
Resolves #714
=> Introduce helper function ResultValue<UniqueHandle<Type, Dispatch>>::asTuple()

VulkanHppGenerator.cpp
When building in Release mode there are several build errors due to use
`-Wall -Werror` and having undefined variables. This CL wraps the
various variables which are only used in `assert` calls to be behind
`#if !defined(NDEBUG)` preprocessor checks.
=> Fixup build errors.

VulkanHppGenerator.cpp
allows
`    auto root = structureChain.get();`
instead of
`    auto root = structureChain.get<RootStructure>();`
Resolves #784
=> Introduce default template type for functions StructureChain::get<T,Which>

VulkanHppGenerator.cpp
With MinGW I get the following error, because constexpr clashes with const:
vulkan.hpp:544:30: error: ‘constexpr T& vk::ArrayWrapper1D<T, N>::operator const’
cannot be overloaded with ‘constexpr const T& vk::ArrayWrapper1D<T, N>::operator const’
544 | VULKAN_HPP_CONSTEXPR T & operator[](int index) VULKAN_HPP_NOEXCEPT
=> Fix T & ArrayWrapper1D::operator[](int index)

VulkanHppGenerator.cpp
User-provided copy constructor and copy assignment operators prevent the class' ABI from being trivial.
=> Default Flags' copy functions

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
This is needed to prevent compiler ambiguities!
Resolves #813
=> Removed default arguments from standard versions of functions, and the shortened function versions of destroy* and free*

README.md, VulkanHppGenerator.cpp
=> Introduce VULKAN_HPP_NO_SPACESHIP_OPERATOR to disable operator<=>() for all structs and classes.

VulkanHppGenerator.cpp, tests/ArrayProxyNoTemporaries/ArrayProxyNoTemporaries.cpp, tests/ArrayProxyNoTemporaries/CMakeLists.txt
=> Make ArrayProxyNoTemporaries complete by marking all constructors getting rvalue references as deleted.

README.md, VulkanHppGenerator.cpp
+ mention that define in the README.md
Resolves #849.
=> Guard definition of VULKAN_HPP_STORAGE_API by an if !defined(); extend internal support to gcc and clang.

VulkanHppGenerator.cpp
Variable definition moved into a block where it is conditionally used.
Fixes #854.
=> [linux][warnings] Fix -Werror=unused-but-set-variable on GCC 10.2, Linux

README.md
The previous is unable. I updated the link to point to the PDF which is readily available
=> Update Vookoo introduction article link

VulkanHppGenerator.cpp
Prevents function offset differences in case of (erroneously) different definitions of platform in separate translation units.
Resolves #887
=> Add placeholder dummy function pointers in DispatchLoaderDynamic for not defined platforms.

VulkanHppGenerator.cpp
=> Correct capitalization of allocateInitializer used in vector-returning functions with provided allocator.

VulkanHppGenerator.cpp
CI is blocked for https://github.com/KhronosGroup/Vulkan-Docs/pull/1529 because the function not recognized by the generator yet.
=> Add vkGetDrmDisplayEXT to the list of function deleted by ObjectRelease

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Make move-constructors and move-assignment operators of vk::raii handle classes noexcept.

VulkanHppGenerator.cpp
Patch from https://github.com/freebsd/freebsd-ports/blob/main/graphics/vulkan-headers/files/patch-include_vulkan_vulkan.hpp
Without this patch, I have a compilation error on FreeBSD: `unsupported platform` . It would be nice to drop the patch from freebsd-ports and include the changes upstream.
=> Support BSD operating systems

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
Only if VULKAN_HPP_RAII_ENABLE_DEFAULT_CONSTRUCTORS is defined, as otherwise those checks are not meaningful.
=> Introduce operator bool() and operator!() on vk::raii handle wrapper classes

README.md, VulkanHppGenerator.cpp
Hello maintainers,
this PR extends Vulkan-HPP's customization capabilities. In my case, since I prefer using designated initializers for Vulkan, having the setter methods around clutters up my IDE's dropdowns. I added a #define option that allows people to remove the setter methods on structs and unions respectively via `VULKAN_HPP_NO_STRUCT_SETTERS` / `VULKAN_HPP_NO_UNION_SETTERS` and also in general via `VULKAN_HPP_NO_SETTERS`.
Also since unions can also be used with designated initializers, I added `VULKAN_HPP_NO_UNION_CONSTRUCTORS` to allow for this when desired. Both that define and `VULKAN_HPP_NO_STRUCT_CONSTRUCTORS` are defined when `VULKAN_HPP_NO_CONSTRUCTORS` is defined.
I also amended the README.md to account for these config options. I think these additions could be useful for …
=> Adding configuration option to disable struct/union setters and union constructors

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
Allows the use of any vk::*Flags type as the key in a std::unordered_map
=> Introduce struct hash<vk::Flags<BitType>>

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp
The assertions fire when the dispatcher and the actual function call is compiled with different VK_HEADER_VERSION.
=> Introduce version check in function wrappers

samples/utils/utils.hpp
Hi,
`std::numeric_limits::*` is used throughout `samples` and `RAII_Samples` but `<limits>` is not included anywhere
I've added `#include <limits>` in `samples/utils/utils.hpp` as it seems to be included by all others
this appears on gcc 11.1.0 on arch linux
this is what the cmake config looks like
```
> cmake -DSAMPLES_BUILD=ON -DTESTS_BUILD=OFF .. && make -j8
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- …
```
=> fix numeric_limits not found, include <limits> in samples/utils.hpp

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Change dispatcher default argument in ObjectDestroy, ObjectFree, ObjectRelease, and PoolFree constructor VULKAN_HPP_DEFAULT_DISPATCHER_ASSIGNMENT

VulkanHppGenerator.cpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_structs.hpp
This name is defined for handles, structures, and unions.
Resolves #1050.
=> Introduce NativeType to get the C-type from the corresponding Cpp-type.

VulkanHppGenerator.cpp, vulkan/vulkan_structs.hpp
Those operators are implicitly declared as constexpr, if they are constexpr-compatible.
Resolves #1055.
=> Remove constexpr specifier from defaulted struct assignment operators.

VulkanHppGenerator.cpp
=> Downgrade attribute "extends" of enum alias elements from required to optional.

RAII_Samples/11_InitShaders/11_InitShaders.cpp, RAII_Samples/CopyBlitImage/CopyBlitImage.cpp, samples/11_InitShaders/11_InitShaders.cpp, samples/CopyBlitImage/CopyBlitImage.cpp, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp
Due to `-Werror` I can only build the samples in debug mode. In release mode (clang-14), the warning about unused variables cause the build to fail.
Is there any preference how a warning about a unused variable should be suppressed?
=> Fix release build of samples: suppress warnings about unused variables

VulkanHppGenerator.cpp, tests/ArrayProxy/ArrayProxy.cpp, tests/ArrayProxyNoTemporaries/ArrayProxyNoTemporaries.cpp, tests/DesignatedInitializers/DesignatedInitializers.cpp, tests/DispatchLoaderStatic/CMakeLists.txt, tests/DispatchLoaderStatic/DispatchLoaderStatic.cpp, vulkan/vulkan.hpp
=> Introduce getDispatchLoaderStatic() to prevent dangling pointers in debug builds.

.github/workflows/set-version-tag.yml, .github/workflows/update-header-pr.yml
Generates PRs like theHamsta#2
As I said, Github will usually not automatically run the CI when commits are created via Github Action Bot. The CI can be triggered manually by closing and the opening the respective PR again.
=> ci: Add .github/workflows/update-header-pr.yml

VulkanHppGenerator.cpp
=> Check for "VK_API_VERSION_m_n" or "VK_VERSION_m_n" in SPIRVCapabilities and SPIRVExtensions

RAII_Samples/RayTracing/RayTracing.cpp, VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
-> vk::raii::Context constructor now either gets
no argument as before, loading vkGetInstanceProcAddr via an internal DynamicLoader;
or a PFN_vkGetInstanceProcAddr, using that to fill the dispatcher
+ changed the sample RAII_Samples/RayTracing to work with VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL defined to be zero
+ fixed the missing destructor call in most of the move assignments of the vk::raii classes
Resolves #1134
=> Use VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL with vk::raii::Context

VulkanHppGenerator.cpp
Add new constructors that accept any vector-like type (with
compatible .data() and .size() methods). Replaces the more specific
constructors accepting std::array, std::vector and std::span.
=> Generalize ArrayProxy and ArrayProxyNoTemporaries constructors

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
Since Vulkan 1.2 this can return nullptr!
=> Filter out to get vkGetInstanceProcAddr in vk::raii::InstanceDispatcher

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
=> Restrict reflect() on structures to non-GCC and GCC version above 7.5.

VulkanHppGenerator.cpp, tests/Hash/Hash.cpp, vulkan/vulkan_hash.hpp
Instead of hashing the pointer, hash the string contents.
Fixes: https://github.com/KhronosGroup/Vulkan-Hpp/issues/1169
=> Fix std::hash specializations for null-terminated strings

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
Commands returning a VkResult with a single success- and multiple error codes, that get no non-const pointers and no vectors, just one const pointer is generalized to support a const void pointer as well, replacing that argument to a const& on a templated type.
=> Generalize command generation for a specific type of commands

VulkanHppGenerator.cpp
This is trying to fix:
https://github.com/KhronosGroup/Vulkan-Hpp/issues/1185
@mikes-lunarg PTAL
=> Fix 'missing braces around initializer' warnings in vulkan_enums.hpp

VulkanHppGenerator.cpp, vulkan/vulkan.hpp
=> Remove the 'allFlags' from the general FlagTraits struct to catch unintentional usage with something different than a supported FlagBitsType.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
Commands returning a VkResult with one or more error codes specified, getting no non-const pointer and zero or more vectors are combined into one function, no matter if it is specified to have one or more success codes.
=> Unified generation of a special type of commands.

VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp
=> Enclose "free" in parenthesis to prevent interference with MSVC's debug free

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Introduce explicit default construction on nullptr_t for vector-based raii-classes.

.github/workflows/update-header-pr.yml
The publication of Vulkan SC (https://www.khronos.org/news/press/khronos-releases-vulkan-safety-critical-1.0-specification-to-deliver-safety-critical-graphics-compute)
confused the update job since it was the most recent tag.
Preliminary solution: only accept tags that match `v1\.`.
=> fix(ci): filter out publications of Vulkan SC on header update

VulkanHppGenerator.cpp
Compiler: clang++-15
```
/home/stephan/projects/Vulkan-Hpp/VulkanHppGenerator.cpp:9105:12: error: unused variable 'constructorCommandIt' [-Werror,-Wunused-variable]
auto constructorCommandIt = m_commands.find( handle.second.constructorIts.front()->first );
^
/home/stephan/projects/Vulkan-Hpp/VulkanHppGenerator.cpp:9732:12: error: unused variable 'handleIt' [-Werror,-Wunused-variable]
auto handleIt = m_handles.find( "Vk" + parentType );
```
=> chore(warnings): fix warnings about unused variables in Release mode

.github/workflows/update-header-pr.yml
Run when tag does not yet exist: https://github.com/theHamsta/Vulkan-Hpp/runs/5461820621?check_suite_focus=true (it actually should exist but I haven't run `git fetch --all --tags` in that revision to actually have any tags locally)
Run when tag already exists: https://github.com/theHamsta/Vulkan-Hpp/runs/5462719659?check_suite_focus=true
=> ci: only create a header update PR if tag does not yet exist

VulkanHppGenerator.cpp
=> Explicitly ignore the result of a call to std::system().

.github/workflows/update-header-pr.yml
The problem: grep was filtering on the commit hashes not the tag names.
One should probably never use bash: https://github.com/ValveSoftware/steam-for-linux/issues/3671
=> ci: fix bash command to retrieve latest Vulkan-Headers commit

README.md, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan.hpp, vulkan/vulkan_handles.hpp
Vulkan handles are not typesafe on 32-bit platforms, but only for
non-dispachable handles. Dispatchable handles are opaque struct pointers
on all platforms, and thus typesafe.
This commit makes all conversions for dispatchable handles implicit,
regardless of VULKAN_HPP_TYPESAFE_CONVERSION setting.
=> Make type conversions implicit for dispatchable handles

README.md, VulkanHppGenerator.cpp, tests/ArrayProxy/ArrayProxy.cpp, tests/ArrayProxyNoTemporaries/ArrayProxyNoTemporaries.cpp, vulkan/vulkan.hpp
Currently `ArrayProxy` doesn't support raw arrays which is annoying. For instance, I have code where I include contents of SPIR-V  shaders (generated with `glslc -mfmt=num`) into `uint32_t[]` array. I can't use `std::array` because I don't know the size in advance. However, since raw arrays are unsupported by `ArrayProxy`, then I have to manually call `setCodeSize` for every shader.
This pull requests adds support for raw arrays, when their size is statically known.
=> Add ArrayProxy constructors with support for raw array with size

VulkanHppGenerator.cpp
In GCC 12, std::exchange is no longer implicitly included in many header files, and so must be explicitly included by including `utility`.
=> Fix missing <utility> import for std::exchange

tests/ArrayProxyNoTemporaries/ArrayProxyNoTemporaries.cpp
=> Resolve warning/error on discarded return value in ArrayProxyNoTemporaries test.

RAII_Samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, RAII_Samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, RAII_Samples/EnumerateDevicesAdvanced/EnumerateDevicesAdvanced.cpp, RAII_Samples/PhysicalDeviceMemoryProperties/PhysicalDeviceMemoryProperties.cpp, RAII_Samples/PhysicalDeviceProperties/PhysicalDeviceProperties.cpp, RAII_Samples/PhysicalDeviceQueueFamilyProperties/PhysicalDeviceQueueFamilyProperties.cpp, RAII_Samples/RayTracing/RayTracing.cpp, RAII_Samples/SurfaceCapabilities/SurfaceCapabilities.cpp, RAII_Samples/SurfaceFormats/SurfaceFormats.cpp, README.md, VulkanHppGenerator.cpp, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/EnumerateDevicesAdvanced/EnumerateDevicesAdvanced.cpp, samples/PhysicalDeviceMemoryProperties/PhysicalDeviceMemoryProperties.cpp, samples/PhysicalDeviceProperties/PhysicalDeviceProperties.cpp, samples/PhysicalDeviceQueueFamilyProperties/PhysicalDeviceQueueFamilyProperties.cpp, samples/RayTracing/RayTracing.cpp, samples/SurfaceCapabilities/SurfaceCapabilities.cpp, samples/SurfaceFormats/SurfaceFormats.cpp, samples/utils/utils.cpp, vulkan/vulkan.hpp, vulkan/vulkan_enums.hpp
Also extend the samples to hold some local version of the needed to_string functions in case VULKAN_HPP_NO_TO_STRING is defined.
=> Introduce VULKAN_HPP_NO_TO_STRING to optionally remove the various vk::to_string functions.

VulkanHppGenerator.cpp, samples/utils/utils.hpp, vulkan/vulkan.hpp, vulkan/vulkan_to_string.hpp
Should help a little on #1325 too.
=> Reduce number of included headers

README.md, VulkanHpp.natvis
=> Introduce VulkanHpp.natvis to nicely format vk::Flags in Visual Studio debugger.

CMakeLists.txt
Apparently, the statement setting ${vulkan_hpp} was removed with along
with the other generated header files the other generated header files.
=> fix: make VULKAN_HPP_RUN_GENERATOR work again

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp, vulkan/vulkan_to_string.hpp
Fixes compilation using clang. 
- For clang-16 on Linux using libstdc++. Include <utility> for `std::exchange` 
```
In file included from /home/stephan/projects/Vulkan-Hpp/debug/RAII_Samples/SurfaceFormats/CMakeFiles/RAII_SurfaceFormats.dir/cmake_pch.hxx:5:
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:28:14: error: no template named 'exchange' in namespace 'std'; did you mean simply 'exchange'?
return std::exchange<T>( obj, std::forward<U>( newValue ) );
^~~~~
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:25:49: note: 'exchange' declared here
VULKAN_HPP_CONSTEXPR_14 VULKAN_HPP_INLINE T exchange( T & obj, U && newValue )
^
/home/stephan/projects/Vulkan-Hpp/vulkan/vulkan_raii.hpp:28:14: error: no template named 'exchange' in namespace 'std'; did you mean simply …
```
=> Fix clang bugs

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_raii.hpp
In that case, no improved constructor and no improved setters are generated.
Plus some minor cleanup.
Resolves #1430.
=> Support structs holding arrays of data, where the data size is given by a pointer-type.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
To explicitly default the copy assignment operator is only needed, if there are other constructors. Otherwise, some compilers warn about it.
Resolves #1397.
=> Move explicitly defaulted copy assignment operators of structs into !defined(VULKAN_HPP_NO_STRUCT_CONSTRUCTORS) section

VulkanHppGenerator.cpp
=> Add missing braces in union constructors on array members.

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp
=> Handle potential shadowing of function parameter name "objectType" with class member.

.github/workflows/ci-macos.yml, .github/workflows/ci-ubuntu.yml, .github/workflows/ci-windows.yml, .github/workflows/set-version-tag.yml, .github/workflows/update-header-pr.yml
From https://github.com/KhronosGroup/Vulkan-Hpp/actions/runs/3932322410
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, ashutoshvarma/setup-ninja@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Update actions/checkout in GitHub Actions

.github/workflows/ci-macos.yml
MacOS wasn't probably intended to be special. Run MacOS CI only on PRs like Windows and Ubuntu
Now they are all the same
=> ci: only run ci-macos on PRs (like ci-ubuntu/ci-windows)

.github/workflows/update-header-pr.yml
- Run without `git fetch --all --tags`: https://github.com/theHamsta/Vulkan-Hpp/actions/runs/4221771719/jobs/7329463344
- Run with `git fetch --all --tags`: https://github.com/theHamsta/Vulkan-Hpp/actions/runs/4221781287/jobs/7329484407 resulting in this PR https://github.com/theHamsta/Vulkan-Hpp/pull/19
=> ci: fix update-header-pr (tags were not fetched)

.github/workflows/ci-windows.yml
This avoids a deprecation warning about Node.js 12 as shown here https://github.com/KhronosGroup/Vulkan-Hpp/actions/runs/4222600167
=> ci: bump setup-msvc-dev to v2

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/EnableBetaExtensions/EnableBetaExtensions.cpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp
=> Fix wrong usage of 'structureChains' in generating functions returning a StructureChain and a vector of data.

snippets/StructureChain.hpp, tests/StructureChain/StructureChain.cpp, vulkan/vulkan.hpp
Resolves #1575.
Resolves #1586.
=> Introduce function StructureChain::assign to assign a complete struct in a StructureChain without modifying the chaining.

snippets/ResultValue.hpp, tests/UniqueHandle/UniqueHandle.cpp, vulkan/vulkan.hpp
Resolves #1577.
Before this change, when assigning an l-value of type `vk::ResultValue<vk::UniqueStuff>` to a `std::tuple<vk::Result,vk::UniqueStuff>` using the `asTuple()`-function, the `vk::UniqueStuff` was implicitly moved from the `vk::ResultValue` to the `std::tuple`.
As that might be unexpected behaviour, that function is marked as deprecated.
Instead, a corresponding `asTuple()`-function working on an r-value is introduced. Using that requires the user to explicitly `std::move` the `vk::ResultValue`.
That is, instead of
`auto trv = rv.asTuple();`
you need to code as
`auto trv = std::move( rv ).asTuple();`
Note, though, that independently of this change, with C++17 you can just use designated initializers like this:
`auto [r,v] = std::move(rv);`
=> Mark vk::ResultValue::asTuple() & as deprecated, introduce vk::ResultValue::asTuple() &&

RAII_Samples/SurfaceCapabilities/SurfaceCapabilities.cpp, VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
This change allows using the default move assignment operator with aggregates of vk::raii-handles, moving the actual destruction of the vk::raii-handles from the move assignment to the destruction of the moved-from aggregate.
Resolves #1588.
=> Change move assignment operators of vk::raii handles from using std::exchange to using std::swap

CMakeLists.txt, VulkanHppGenerator.cpp, snippets/defines.hpp, tests/Cpp20Modules/CMakeLists.txt, vulkan/vulkan.cppm, vulkan/vulkan.hpp
Resolves #1614 and partially resolves #1615. 
- Removed nested `export` keyword for `vk::raii` namespace in C++ module file
- Fixed macro in `vulkan.cppm` for `vk::DynamicLoader`: changed from `VULKAN_HPP_DYNAMIC_LOADER_TOOL` to `VULKAN_HPP_ENABLE_DYNAMIC_LOADER_TOOL`  
- Moved `VulkanHppModule` library target before generator in top-level `CMakeLists.txt`
- Fixed `CMakeLists.txt` for `Cpp20Modules` executable target
=> Bug fixes for `vulkan.cppm`

README.md, samples/16_Vulkan_1_1/16_Vulkan_1_1.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/PushDescriptors/PushDescriptors.cpp, samples/SurfaceCapabilities/SurfaceCapabilities.cpp
Mention in README.md, that vk::DynamicLoader needs to be kept alive until after the last call into vulkan in the program.
Plus some cleanup on that thing.
Resolves #1620.
=> Update in README.md

samples/utils/utils.cpp
> The application should always return VK_FALSE. The VK_TRUE value is reserved for use in layer development.
Reference: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html#_description
=> Fix debug layers callback return value

CMakeLists.txt
When using `VULKAN_HPP_ENABLE_EXPERIMENTAL_CPP20_MODULES=ON` with CMake 3.27.0 or 3.27.1, you will get a very confusing error message:
```
CMake Error at CMakeLists.txt:346 (target_sources):
target_sources File set TYPE may only be "HEADERS"
```
This is because the value of `CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API` is not updated to the correct value, disabling all experimental CMake features.
This PR adds the value for 3.27.X and triggers an error for higher CMake versions where this feature needs to be revised and `CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API` if the feature is still experimental.
The error message will look similar to this one (simulated for CMake 3.27.1)
```
CMake Error at CMakeLists.txt:30 (message):
VULKAN_HPP_ENABLE_EXPERIMENTAL_CPP20_MODULES is currently not supported …
```
=> fix: add support for C++20 modules for CMake 3.27.0/3.27.1

VulkanHppGenerator.cpp, vulkan/vulkan.cppm, vulkan/vulkansc.cppm
=> Guard vk::raii names in vulkan.cppm just as in vulkan_raii.hpp.

snippets/DynamicLoader.hpp, snippets/includes.hpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
During last 23 years the QNX Neutrino microkernel was active, __QNXNTO__ macro belongs to it. Now QNX Muon microkernel is under development, so __QNX__ macro covers both versions: Neutrino and Muon.
First public announce of QNX Muon was here: https://blogs.blackberry.com/en/2023/04/get-in-the-sdv-podcast-from-blackberry-season-2-episode-3
=> Switch __QNXNTO__ macro check to __QNX__

.github/workflows/ci-macos.yml, .github/workflows/ci-ubuntu.yml, .github/workflows/ci-windows.yml, .github/workflows/set-version-tag.yml, .github/workflows/update-header-pr.yml
Update the used workflows to their newest version to suppress deprecation warnings as in https://github.com/KhronosGroup/Vulkan-Hpp/actions/runs/6319631419
Smoke test for the update-headers-pr seems to still run as before
https://github.com/theHamsta/Vulkan-Hpp/actions/runs/6325102376/job/17175926924
Also replace
```
-DSAMPLES_BUILD=OFF
-DTESTS_BUILD=OFF
```
with the actually existing CMake options.
=> Update workflow deps

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp
Used to add some special handling capabilities for specific commands.
Resolves #1655.
=> Extend command generation to support not returning some return stuff and not templatizing a void pointer.

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_raii.hpp
=> Introduce using CppType type-trait for raii-classes, add two helper functions to filter the cpp-types out of a vector of raii-types.

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
In `vulkan.cppm`, `vk::UniqueHandle` and `vk::SharedHandle` are under `#if !defined( VULKAN_HPP_DISABLE_ENHANCED_MODE )`, even though they're actually controlled by `VULKAN_HPP_NO_SMART_HANDLE` in the headers.
This PR fixes that issue.
I actually wanted to build with `VULKAN_HPP_NO_SMART_HANDLE`, because I get an internal compiler error with MSVC otherwise :) Haven't been able to figure out what exactly causes it yet
=> Fix C++20 module build with -DVULKAN_HPP_NO_SMART_HANDLE

CMakeLists.txt
This adjusts some uses of cmake variables, so that Vulkan-Hpp can be built as a subdirectory of another project.
=> Use add_subdirectory-friendly CMAKE variables

vk_raii_ProgrammingGuide.md
=> Fix documentation on existance of some copyable vk::raii classes

snippets/ArrayWrapper1D.hpp, tests/ArrayWrapper/ArrayWrapper.cpp, tests/ArrayWrapper/CMakeLists.txt, tests/CMakeLists.txt, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Improve implicit conversion operators of vk::ArrayWrapper1D on char type; added constructors from std::string and std::string_view

tests/ArrayWrapper/ArrayWrapper.cpp
=> Fix ArrayWrapper test program: don't use std::string_literals to be C++11 conform.

RAII_Samples/DynamicUniform/DynamicUniform.cpp
Hi! The samples in this repository are a gem to anyone learning Vulkan.
I stumbled upon a subtle logical error.
The chosen `vk::Format` in the DynamicUniform RAII sample does not match `coloredCubeData`, which results in some information about color being discarded.
The corresponding [sample](https://github.com/KhronosGroup/Vulkan-Hpp/blob/4cb522cc511de9826b0691361ef2c786d3582b07/samples/DynamicUniform/DynamicUniform.cpp#L140) from the `vk` namespace uses the correct format.
Since these code snippets carry educational purpose, we should fix this issue to avoid confusion.
=> Use vk::Format that matches coloredCubeData in DynamicUniform RAII sample

VulkanHppGenerator.cpp, vulkan/vulkan_extension_inspection.hpp, vulkan/vulkansc_extension_inspection.hpp
Hi! This adds some missing includes to `vulkan_extension_inspection.hpp` - when disabling enhanced mode they're not pulled in from `vulkan.hpp`, resulting in build errors in `vulkan.cppm`. Thanks!
=> Add missing includes

VulkanHppGenerator.cpp
=> Fix usage of wrong command name when determining the skip count for that command

.github/workflows/ci-ubuntu.yml, CMakeLists.txt
Note: under Linux, none of clang++13, clang++14, g++-9, and g++-10 could successfully compile for C++23!
=> Use the actual CMAKE_CXX_STANDARD provided by the workflow.

VulkanHppGenerator.cpp
=> Downgrade error on multiple identical "depends" attributes for "require" sections for an extension to a warning.

README.md
- Fix CMake instructions for the C++20 named module
- Provided examples on module config
- Elaborated on dynamic dispatcher setup for the module
Resolves #1753.
=> C++20 named module documentation updates

README.md, snippets/includes.hpp
Added `VULKAN_HPP_NO_WIN32_PROTOTYPES` preprocessor condition which disables dynamic loader win32 types declaration.
=> Added VULKAN_HPP_NO_WIN32_PROTOTYPES preprocessor condition 

vk_raii_ProgrammingGuide.md
Replaces VULKAN_HPP_NO_EXC**PE**TIONS with VULKAN_HPP_NO_EXC**EP**TIONS
=> Fix typo in vk_raii_ProgrammingGuide.md

VulkanHppGenerator.cpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp
=> Add special handling for call sequence in commands for vkGetDeviceFaultInfoEXT

VulkanHppGenerator.cpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_funcs.hpp, vulkan/vulkansc_raii.hpp
As a struct vk::DeviceFaultInfoEXT is filled with pointers to dynamically allocated memory when the function vk::Device::getFaultInfoEXT() is called, it supports ownership of that memory now by providing a destructor freeing that memory.
To correctly support that ownership of memory, the copy constructor and assignment operators are deleted, instead some move constructor and assignment operators are introduced.
=> Use some special handling for struct vk::DeviceFaultInfoEXT

snippets/StructureChain.hpp, tests/StructureChain/StructureChain.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
Use `auto`, instead of `void *`, to also support structures with `const void *` as type for `pNext`.
Resolves #1797.
=> Fix issue with vk::StructureChain::assign

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_raii.hpp
Replaced with `using std::exchange`
```
namespace sample
{
using std::exchange;
void func()
{
std::vector<vk::raii::CommandBuffer> bufs = ...;
exchange(bufs, {}); //< that line causes 'ambiguous call' compiler error
}
}
```
=> Disabled `vk::raii::exchange()` implementation for C++14 or newer

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp
- do not create enhanced struct constructors, if the length of an array is determined by a member of that struct that is a pointer;
- check for error if a command parameter has a len attribute, but is not a pointer
- accept sync access and sync stage to be multiply aliased.
=> Three fixes:

RAII_Samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp, tests/UniqueHandle/UniqueHandle.cpp
Correctly handle a zero max image count in VkSurfaceCapabilitiesKHR which indicates no upper limit to the number of images in a swapchain.
_"maxImageCount is the maximum number of images the specified device supports for a swapchain created for the surface, and will be either 0, or greater than or equal to minImageCount. A value of 0 means that there is no limit on the number of images, though there may be limits related to the total amount of memory used by presentable images."_
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html
Fixes validation error VUID-VkSwapchainCreateInfoKHR-minImageCount-01271
=> Fixed Validation Error From Zero MaxImageCount in VkSurfaceCapabilitiesKHR

README.md, VulkanHppGenerator.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
Resolves #1860.
Plus a minor fix in Readme.md, Resolves #1854.
=> Change default for template non-type parameter value of struct CppType from 0 to Type{}.

RAII_Samples/16_Vulkan_1_1/16_Vulkan_1_1.cpp
Fixed a small typo where, in the RAII API versioning sample, the instance was being created without the version parameter.
=> RAII Sample 16 fix

CMakeLists.txt, RAII_Samples/05_InitSwapchain/05_InitSwapchain.cpp, RAII_Samples/utils/utils.hpp, VulkanHppGenerator.cpp, samples/05_InitSwapchain/05_InitSwapchain.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp, snippets/ArrayWrapper1D.hpp, tests/UniqueHandle/UniqueHandle.cpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp, vulkan/vulkansc_structs.hpp
=> Make generated headers resistant to missing definition of NOMINMAX for windows builds.

VulkanHppGenerator.cpp, vulkan/vulkan.cppm, vulkan/vulkansc.cppm
=> Don't export symbols in `vk::detail` namespace

snippets/DynamicLoader.hpp, vulkan/vulkan.hpp, vulkan/vulkansc.hpp
=> Adjust loading procedure of the vk::detail::DynamicLoader on MacOS

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, tests/Cpp20Modules/Cpp20Modules.cpp, tests/CppStdModule/CppStdModule.cpp, vulkan/vulkan.cppm, vulkan/vulkansc.cppm, vulkan/vulkansc_extension_inspection.hpp
=> Add specializations of std::hash for all the structs and handles in the vk-namespace.

VulkanHppGenerator.cpp, tests/Handles/Handles.cpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp, vulkan/vulkansc_handles.hpp, vulkan/vulkansc_raii.hpp
The comparison operators for vk-handles are not need, as due the implicit cast operators comparisons are passed on to the corresponding C-handle types.
Resolves #1996.
=> Add comparison operators for vk::raii handles, remove them for vk handles

RAII_Samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, RAII_Samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, samples/CreateDebugUtilsMessenger/CreateDebugUtilsMessenger.cpp, samples/EnableValidationWithCallback/EnableValidationWithCallback.cpp, samples/utils/utils.cpp, samples/utils/utils.hpp
Setters and constructors using the C-type funcpointers are marked as deprecated. They will be removed, probably around December 2025.
=> Introduce vk-version of the funcpointers

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
This type is used as a bit field in some structures, which can't be mimiced by a vk-data type!
=> Export the C-type VkGeometryInstanceFlagsKHR in vulkan.cppm.

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
Adding this assertion in #1978 was wrong, as a `vk::raii::DescriptorPool` can also be used to create `vk::DescriptorSet`s.
The "correct" assertion would be located in the `vk::raii::DescriptorSet` constructor/create function. But we can't get the required information out of what we have there.
=> Remove special assertion on eFreeDescriptorSet in function Device::createDescriptorPool

CMakeLists.txt
Resolves #2037 
New CMake option `VULKAN_HPP_GENERATOR_BUILD` to control the creation of both `VulkanHppGenerator` and `VideoHppGenerator` targets, defaulting to `ON` as to not break anything.
Naming was based on `VULKAN_HPP_SAMPLES_BUILD` and `VULKAN_HPP_TESTS_BUILD`, could otherwise rename to `VULKAN_HPP_BUILD_GENERATOR` to fit `VULKAN_HPP_RUN_GENERATOR` naming scheme.
Also created the `Vulkan-Hpp` interface target, aliased as `Vulkan::Hpp` for those just looking to get the include directory. Naming is akin to the Vulkan-Headers with their `Vulkan-Headers` interface target, aliased as `Vulkan::Headers`.
The target is always created and it might make sense to use it in the other build targets as a unified way to include the generated headers? Otherwise it can be hidden behind a CMake …
=> Isolating generator targets and creating header-only interface target

CMakeLists.txt
Created an alias target similar to Vulkan::Hpp, while also renaming the Vulkan-Hpp target to VulkanHpp to be similar in name to VulkanHppModule.
Moving VulkanHpp target above module target allows linking to it for its include directory.
=> CMake: Alias for c++20 modules target

README.md
It ain't much, but it's honest work
=> README: Fixing extension inspection typo and RAII-classes title format

.clang-format_14
=> Make BreakBeforeConceptDeclarations a boolean for clang-format 14.

README.md
Sorted `VULKAN_HPP_NO_TO_STRING` alphabetically alongside the other configuration options, placing it after `VULKAN_HPP_NO_SPACESHIP_OPERATOR`
=> README: Fixed sorting order for `VULKAN_HPP_NO_TO_STRING`

CMakeLists.txt
Using following priority to determine where to get the C headers:
1. `Vulkan-Headers` subdirectory, if submodule is pulled
2. `Vulkan::Headers` target, if present (e.g. via `FindVulkan` or `add_subdirectory`)
3. `Vulkan::Headers` target, requiring `FindVulkan`
=> CMake: Offer multiple choices for Vulkan C headers

snippets/CppModuleFileTemplate.hpp, vulkan/vulkan.cppm
=> C++20 module: Hide to_string behind VULKAN_HPP_NO_TO_STRING

CMakeLists.txt
#2075 lead to CI failures on https://gitlab.khronos.org/ !
=> Revert MR #2075

snippets/SharedDestroy.hpp, vulkan/vulkan_shared.hpp
Clang 19.1.7 throws warnings due to the reinterpret cast to `m_destroy`.
Suppression implemented akin to the GCC one.
Used `defined( __clang__ ) && !defined( __INTEL_COMPILER )` without `!defined( __GNUC__ )`, as clang defines it to signify compatible GCC versions.
Also checking clang major version via `(__clang_major__ >= 13)`, as 13 is where the `-Wcast-function-type` was first introduced.
=> Suppress clang warning `-Wcast-function-type` for shared destroy

XMLHelper.hpp
Window CI sometimes fails due to "permission errors":
<details>
<summary>Output</summary>
```batch
run VulkanHppGenerator
clang-format version 18.1.8
VulkanHppGenerator: Found VulkanHppGenerator: Loading D:\a\Vulkan-Hpp\Vulkan-Hpp\Vulkan-Headers\registry\vk.xml
VulkanHppGenerator: Parsing D:\a\Vulkan-Hpp\Vulkan-Hpp\Vulkan-Headers\registry\vk.xml
VulkanHppGenerator: Spec warning on line 642: enum <VkDeviceCreateFlagBits> not required in any feature or extension!
VulkanHppGenerator: Spec warning on line 798: enum <VkImageFormatConstraintsFlagBitsFUCHSIA> not required in any feature or extension!
VulkanHppGenerator: Spec warning on line 621: enum <VkQueryPoolCreateFlagBits> not required in any feature or extension!
VulkanHppGenerator: Spec warning on line 700: enum …
```
=> CI: Attempt to fix build failure on windows

XMLHelper.hpp
Seeing how it failed again, I dug a bit deeper into what could cause it.
Flushing the `std::ofstream` seems to only guarantee synchronization for the current application. The OS has to decide what to actually do, where Windows seems to have some trouble, as we spawn a separate process with `std::system`.
From what I found, there are two solutions, one being a hacky one that someone suggested on SO:
https://stackoverflow.com/a/9667875
which essentially just opens a new stream, which seems to force windows to actually finalize the write to disk.
There might be a better solution though, looking at the spec of `std::system` itself:
https://en.cppreference.com/w/cpp/utility/program/system
> _An explicit flush of [std::cout](https://en.cppreference.com/w/cpp/io/cout) is also necessary before a …
=> CI: Another attempt to fix windows ci..

VulkanHppGenerator.cpp
These new operators allow the Vulkan-Hpp struct classes to be more easily used directly with the Vulkan C API.
For example, instead of this:
```c++
vk::BufferCreateInfo bufferInfo { .size{sizeof vertexData}, .usage{vk::BufferUsageFlagBits::eVertexBuffer} };
vmaCreateBuffer(allocator, &static_cast<VkBufferCreateInfo const &>(bufferInfo), &bufferAllocationInfo, &vertexBuffer, &vertexBufferAllocation, nullptr);
```
Apps can do this:
```c++
vk::BufferCreateInfo bufferInfo { .size{sizeof vertexData}, .usage{vk::BufferUsageFlagBits::eVertexBuffer} };
vmaCreateBuffer(allocator, bufferInfo, &bufferAllocationInfo, &vertexBuffer, &vertexBufferAllocation, nullptr);
```
=> Add additional type conversion operators to the struct classes to make it easier to interoperate with the Vulkan C API

snippets/CppModuleFileTemplate.hpp, vulkan/vulkan.cppm
Previously, the `VkGeometryInstanceFlagsKHR` symbol was exported like this:
```cpp
export VkGeometryInstanceFlagsKHR;
```
but as this does not declare anything, compilers will complain (clang warning, gcc error):
```
vulkan/vulkan.cppm:8490:8: warning: declaration does not declare anything [-Wmissing-declarations]
8490 | export VkGeometryInstanceFlagsKHR;
```
and, based on the comment, I assume the symbol was meant to be exported like this into global namespace:
```cpp
export using ::VkGeometryInstanceFlagsKHR;
```
=> C++Module: Fix export of `VkGeometryInstanceFlagsKHR` symbol

VulkanHppGenerator.cpp, vulkan/vulkan_to_string.hpp
Currently, these functions are implemented rather inefficiently. Here's a random one to demonstrate:
```cpp
VULKAN_HPP_INLINE std::string to_string( CommandBufferUsageFlags value )
{
if ( !value )
return "{}";
std::string result;
if ( value & CommandBufferUsageFlagBits::eOneTimeSubmit )
result += "OneTimeSubmit | ";
if ( value & CommandBufferUsageFlagBits::eRenderPassContinue )
result += "RenderPassContinue | ";
if ( value & CommandBufferUsageFlagBits::eSimultaneousUse )
result += "SimultaneousUse | ";
return "{ " + result.substr( 0, result.size() - 3 ) + " }";
}
```
The `substr()` call incurs a copy of the string.
Then, because we _prepend_ `{`, all the string's contents need to be memmoved up in memory.
And overall we're not taking advantage of NRVO.
With a few tweaks, we can solve all …
=> Optimize `to_string` functions for enums

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
`getExtensionDepends` was temporarily removed in #2094 and this simply does the same for the cppm module, which fails to compile otherwise.
=> cppm: Temporarily remove extension dependency inspection as in #2094

VulkanHppGenerator.cpp, vulkan/vulkan_enums.hpp
=> Add WrappedType to FlagTraits<*FlagBits> to generically get from vk::*FlagBits to Vk*FlagBits at compile-time.

VulkanHppGenerator.cpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp, vulkan/vulkan_raii.hpp
The command `vkExportMetalObjectsEXT` mixes input and output values in its structure chain and thus can't simply return a `vk::StructureChain`. Instead, it takes a (non-const) reference to the chain, just like the standard version takes a (non-const) pointer.
Resolves #2141.
=> Add some special handling for command vkExportMetalObjectsEXT

VulkanHppGenerator.cpp, snippets/FormatTraits.hpp, vulkan/vulkan.cppm, vulkan/vulkan_format_traits.hpp
New functions: `getDepthFormats`, `getDepthStencilFormats`, `getStencilFormats`, `hasDepthComponent`, `hasStencilComponent`.
Moved the `vulkan_format_traits` template into a snippet `FormatTraits.hpp`
=> Introduce new format traits functions

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
Under Windows, we need to export the `defaultDispatchLoaderDynamic` symbol, as simply importing vulkan_hpp will not provide it without including the macro header in every .cppm file that imports vulkan_hpp. I'm actually suprised it worked under Clang. It wasn't caught by the tests, as they manually include `vulkan_hpp_macros.hpp` for dynamic storage, so the symbol will always be present in that single .cppm source.
This also enables the storage placement with modules to be handled without the macro header inclusion:
```cpp
import vulkan_hpp;
namespace vk::detail {
DispatchLoaderDynamic defaultDispatchLoaderDynamic;
}
```
=> C++20 Module: Fixing dynamic dispatch on Windows MSVC

CMakeLists.txt
In the current glslang version 13.0.0, `SpvBuilder.h` is missing `#include <cstdint>`, which can cause compilers to complain about the use of uint32_t in that header. I got an error with both Clang 19.1.7 and GCC 15.1.1 when building tests and samples.
I also disabled `ENABLE_OPT` for glslang, since we would either have to add SPIRV_Tools as a submodule or rely on find_package for it using ALLOW_EXTERNAL_SPIRV_TOOLS. Otherwise we would get this CMake error:
```
CMake Error at glslang/CMakeLists.txt:296 (message):
ENABLE_OPT set but SPIR-V tools not found.  Please run
update_glslang_sources.py, set the ALLOW_EXTERNAL_SPIRV_TOOLS option to use
a local install of SPIRV-Tools, or set ENABLE_OPT=0.
```
I think not having the glslang opt enabled is fine, since its for testing purposes anyways.
=> Update submodule glslang to version 15.3.0

VulkanHppGenerator.cpp, VulkanHppGenerator.hpp, snippets/CppModuleFileTemplate.hpp, vulkan/vulkan.cppm
Resolves #2154
Some people will want to have access to the PFN_* symbols when importing vulkan.cppm. I've updated the generator to add these symbols under the `PFN TYPES` group, directly after `BASE TYPES`. Let me know if these should be placed somewhere else (particularly since they are not part of the vk:: namespace).
The new function `appendCppModulePFNCommands` to construct the string data is basically a cut down version of `appendDispatchLoaderDynamicCommands`, since the output was very similar.
=> C++20 Module: Exporting PFN_* symbols

snippets/includes.hpp, vulkan/vulkan.hpp
Fix the compilation error problem in #2164 using what's described in the issue.
=> Fix undefined `assert` when using `std` module

VulkanHppGenerator.cpp
A small fix to initialise the `ppEnabledLayerNames` and `enabledLayerCount` members of `vk::DeviceCreateInfo` from the passed `std::vector`.  These parameters are deprecated but they should still be initialised cleanly.
This reverts some of the changes in d16c62670b02dd3292aa8711702efebfc634645f
Tested on:
Dell Precision 5690 (Meteor Lake-P)
Ubuntu 24.04
Vulkan 1.4.313
=> Fix for uninitialised deprecated members in DeviceCreateInfo constructor

RAII_Samples/utils/utils.hpp, samples/utils/utils.hpp
On the Meteor Lake-P GPU the driver reports maxImageCount as 0, which causes the `vk::su::clamp()` function to pass 0 into the `SwapchainCreateInfoKHR` constructor.  This change catches this and forces it to be greater than or equal to the minimum reported.
Tested on:
Dell Precision 5690 (Meteor Lake-P)
Ubuntu 24.04
Vulkan 1.4.313
=> Fix SwapchainCreateInfoKHR where some drivers report maxImageCount as 0

VulkanHppGenerator.cpp, vulkan/vulkan_raii.hpp
=> Add "standard" implementation for raii commands returning a structure chain.

.github/workflows/ci-ubuntu-ext.yml
This new CI is supposed to test newest compiler versions that are not available on the runners by default yet, hopefully catching errors before they make it into stable distro releases.
It pulls newest builds for clang and cmake from the publishers apt repos.
The plan is to also use these to test `import std` in the near future, as newer version of CMake are required (min `3.30`, though much more stable in `4.1`).
=> CI: Added bleeding-edge ubuntu ci with clang 19/20 and newest cmake (4.1)

snippets/EnumsHppTemplate.hpp, snippets/FuncsHppTemplate.hpp, snippets/HandlesHppTemplate.hpp, snippets/StructsHppTemplate.hpp, vulkan/vulkan_enums.hpp, vulkan/vulkan_funcs.hpp, vulkan/vulkan_handles.hpp
This builds on #1936 and #1939, correcting typos and file paths, as well as addressing false-positive unused include warnings.
As @rwols pointed out in [this comment](https://github.com/KhronosGroup/Vulkan-Hpp/pull/1939#discussion_r2346016464), the IWYU [private](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-private) pragma uses a comma, not a semicolon. I have corrected this and also updated the paths from `"vulkan.hpp"` to `"vulkan/vulkan.hpp"`.
~In addition to this, I've added IWYU [export](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export) pragmas to `vulkan/vulkan.hpp` so that tools like clangd no longer incorrectly flag it as being unused.~
Edit: It appears the …
=> Fix: Correct IWYU pragmas

VulkanHppGenerator.cpp, vulkan/vulkan.cppm
Another request for [VMA-Hpp](https://github.com/YaaZ/VulkanMemoryAllocator-Hpp):
VMA functions return `VkResult` codes and VMA-Hpp wraps them the same way Vulkan-Hpp do.
Now we have to copy the implementation of `createResultValueType`, `resultCheck` and `throwResultException`, as it's not exported from the `.cppm`. Maintaining this copy manually is burdensome, as sometimes error codes get deprecated and removed, breaking compilation.
It would be really nice if VMA-Hpp could use these functions directly from Vulkan-Hpp, maybe it could be helpful in other use cases where people have to deal with result codes.
I essentially implemented [this suggestion](https://github.com/KhronosGroup/Vulkan-Hpp/pull/1931#issuecomment-2273060760) to export the symbols under `vk::detail` namespace.
=> Export ResultValue related functions

snippets/CppmTemplate.hpp, vulkan/vulkan.cppm
Simple check for whether `VULKAN_HPP_ENABLE_STD_MODULE` is already defined to prevent warnings about duplicate definitions. Should be kept until Clang fix their `__cpp_lib_modules` shenanigans, which requires manual definition of said macro.
=> C++Module: Added redefinition guard for `VULKAN_HPP_ENABLE_STD_MODULE`

VulkanHppGenerator.cpp, tests/DesignatedInitializers/DesignatedInitializers.cpp
=> Extend test DesignatedInitializers to use a struct with deprectated members.
